#define new fdos_new
#ifndef _Static_assert
#define _Static_assert static_assert
#define FDOS_LOCAL_STATIC_ASSERT_MACRO 1
#endif
extern "C" {
#include "hdrs.h"
}
#ifdef FDOS_LOCAL_STATIC_ASSERT_MACRO
#undef _Static_assert
#undef FDOS_LOCAL_STATIC_ASSERT_MACRO
#endif
#undef new
#ifdef load
#undef load
#endif

#include "guest_ref.hpp"
#include "path_guest.h"

using fdos_guest::bpb_ref;
using fdos_guest::cds_ref;
using fdos_guest::dhdr_ref;
using fdos_guest::dos_data_ref;
using fdos_guest::dpb_ref;
using fdos_guest::lol_ref;
using fdos_guest::psp_ref;
using fdos_guest::request_ref;
using fdos_guest::sft_ref;
using fdos_guest::sfttbl_ref;

extern "C" {

static const char *media_check_source = "?";

static constexpr fdos_guest::linear_t media_req_linear =
    (static_cast<fdos_guest::linear_t>(DOS_PSP) << 4) + X86_INTERNAL_DATA_OFF +
    offsetof(dos_data, MediaReqHdr);
static const request_ref media_req(media_req_linear);
static const dos_data_ref fatfs_idata(
    (static_cast<fdos_guest::linear_t>(DOS_PSP) << 4) + X86_INTERNAL_DATA_OFF);
static const lol_ref fatfs_lol(
    (static_cast<fdos_guest::linear_t>(DOS_PSP) << 4) + 0x08F0u);
static const dos_far_ptr media_req_far =
    MK_FP(DOS_PSP, X86_INTERNAL_DATA_OFF + offsetof(dos_data, MediaReqHdr));

static int cds_current_path_equals_ref(dos_far_ptr p, fdos_path_ref path)
{
  size_t i;
  if (far_is_null(p))
    return 0;
  char current[MAX_CDSPATH];
  cds_ref(p).copy_current_path(current, sizeof(current));
  for (i = 0; i < sizeof(current); ++i)
  {
    const UBYTE a = fdos_path_get(path, i);
    const UBYTE b = (UBYTE)current[i];
    if (a != b)
      return 0;
    if (a == 0)
      return 1;
  }
  return 0;
}

#if DIAG
extern volatile unsigned int dos_diag_kernel_code;
#endif

/*
    fnode scratch nodes - internal file nodes used while servicing a
    single DOS API call (open/read/write/seek/close/etc). No guest code
    or DOS API ever holds a reference to an f_node, only to the SFT index
    that
    sft_to_fnode()/fnode_to_sft() below translate to/from one.

    Migrated from globals.h (GLOBAL struct f_node fnode[2]). fnode[0]
    is used for ordinary single-file operations; fnode[1] is only
    needed by operations that touch two files at once (rename, and
    DOS's "move within filesystem"), neither of which is implemented
    yet - but the second slot is kept so code matches the original's
    indexing (fnode_slot(0) / fnode_slot(1)).

    These two scratch nodes now live in GUEST RAM (DynAlloc), not native
    SRAM, to reclaim ~136 bytes of the scarce 520 KB SRAM. That is safe
    for exactly the reason the previous comment gives - nothing guest-side
    ever holds an f_node pointer - AND all of f_node's own pointer fields
    (f_dpb, f_dmp) already target guest RAM (the DPB chain, and the SDA
    dmatch / DynAlloc'd LFN slots respectively), so an f_node is fully
    self-consistent wherever it lives. Same proven pattern as lfnapi.c's
    lfn_fnode_slot table. fnode_slot(i) returns the native view.
*/
/* f_node is kernel-only transient state.  It must not live in pageable guest
   RAM: callers keep the pointer across FAT/cache/device accesses. */
static struct f_node fnode[2];

void fnode_init(void)
{
}

f_node_ptr fnode_slot(int i)
{
  return &fnode[i];
}

/* /// Added - Ron Cemer */
/* If more than one SFT has a file open, and a write
   occurs, this function must be called to propagate the
   results of that write to the other f_nodes which have
   that file open.  Note that this function only has an
   effect if SHARE is installed.  This is for compatibility
   reasons, since DOS without SHARE does not share changes
   between two or more open instances of the same file
   unless these instances were generated by dup() or dup2().

    Migrated from fatfs.c.
*/
STATIC int merge_file_changes(f_node_ptr fnp, int collect)
{
  int i = 0;
  const dos_far_ptr fnp_dpb_far = fnp->f_dpb;

  if (!IsShareInstalled(FALSE))
    return SUCCESS;

  for (dos_far_ptr block = fatfs_lol.sfthead(); !far_is_end(block); )
  {
    const sfttbl_ref table(block);
    const UWORD count = table.count();

    for (UWORD j = 0; j < count; ++j, ++i)
    {
      const sft_ref sftp(table.entry(j));
      const dos_far_ptr entry_dcb = sftp.dcb();

      if (i != fnp->f_sft_idx && sftp.count() != 0
          && FP_SEG(fnp_dpb_far) == FP_SEG(entry_dcb)
          && FP_OFF(fnp_dpb_far) == FP_OFF(entry_dcb)
          && (fnp->f_dir.dir_attrib & D_VOLID) == 0
          && (sftp.attrib() & D_VOLID) == 0
          && fnp->f_diridx == sftp.dir_index()
          && fnp->f_dirsector == sftp.dir_sector())
      {
        if (collect == -1)
        {
          /* DosCloseSft() may remap guest RAM; only linear/far refs survive it. */
          const int rc = DosCloseSft(i, FALSE);
          if (rc != SUCCESS)
            return rc;
        }
        else if (collect)
        {
          if ((sftp.mode() & O_ACCMODE) != RDONLY)
          {
            const CLUSTER start = sftp.start_cluster();
            const ULONG size = sftp.size();
            const ddate date = sftp.date();
            const dtime time = sftp.time();
            setdstart(fnp->f_dpb, &fnp->f_dir, start);
            fnp->f_dir.dir_size = size;
            fnp->f_dir.dir_date = date;
            fnp->f_dir.dir_time = time;
            return SUCCESS;
          }
        }
        else
        {
          const CLUSTER start =
              getdstart(fnp->f_dpb, &fnp->f_dir);
          sftp.start_cluster(start);
          sftp.size(fnp->f_dir.dir_size);
          sftp.date(fnp->f_dir.dir_date);
          sftp.time(fnp->f_dir.dir_time);
        }
      }
    }

    block = table.next();
  }
  return SUCCESS;
}

/*
    sft_to_fnode(fd)/fnode_to_sft(fnp) - copy an open file's state
    between its SFT entry (guest-visible, dos_far_ptr-based) and
    scratch node fnode_slot(0) (used while servicing the call; it lives
    in guest RAM but is reached natively via ARM_PTR).

    Migrated from fatfs.c.
*/
STATIC f_node_ptr sft_to_fnode(int fd)
{
  const dos_far_ptr sft_far = idx_to_sft(fd);
  const sft_ref sftp(sft_far);
  f_node_ptr fnp = fnode_slot(0);
  CLUSTER start_cluster;

  fnp->f_sft_idx = (UBYTE)fd;
  fnp->f_flags = sftp.flags();
  fnp->f_dir.dir_attrib = sftp.attrib();
  sftp.read_name(fnp->f_dir.dir_name);
  fnp->f_dir.dir_time = sftp.time();
  fnp->f_dir.dir_date = sftp.date();
  fnp->f_dir.dir_size = sftp.size();
  fnp->f_dpb = sftp.dcb();
  start_cluster = sftp.start_cluster();
  fnp->f_diridx = sftp.dir_index();
  fnp->f_dirsector = sftp.dir_sector();
  fnp->f_offset = sftp.position();
  fnp->f_cluster = sftp.current_cluster();
#ifdef WITHFAT32
  fnp->f_cluster_offset = sftp.rel_cluster() |
    ((ULONG)sftp.rel_cluster_high() << 16);
#else
  fnp->f_cluster_offset = sftp.rel_cluster();
#endif

  setdstart(fnp->f_dpb, &fnp->f_dir, start_cluster);
  return fnp;
}

/*
    dos_close(fd) - the FAT-level half of closing a file: stamp the
    modification time/date if the file was written and the SFT's
    "date already set" bit isn't set, propagate any in-memory changes
    to other SFTs pointing at the same file, then write the directory
    entry back (dir_write_update(), which - see its comment above -
    only actually writes anything if the file was modified).

    Migrated from fatfs.c verbatim.
*/
COUNT dos_close(COUNT fd)
{
  /* Translate the fd into a useful pointer                       */
  f_node_ptr fnp = sft_to_fnode(fd);

  if (!(fnp->f_flags & SFT_FCLEAN))
  {
    if (!(fnp->f_flags & SFT_FDATE))
    {
      fnp->f_dir.dir_time = dos_gettime();
      fnp->f_dir.dir_date = dos_getdate();
    }

    merge_file_changes(fnp, FALSE);     /* /// Added - Ron Cemer */
  }
  fnp->f_sft_idx = 0xff;

  return dir_write_update(fnp, TRUE) ? SUCCESS : DE_INVLDHNDL;
}

/*
    dos_extend(fnp, emptywrite) - make sure the FAT chain reaches at
    least up to fnp->f_offset before a write starts (fnp->f_offset was
    already positioned by the preceding lseek/DTA logic; dir_size may
    still be smaller, e.g. after a seek past EOF, or on the very first
    write to a freshly created empty file).

    CAUTION (2026-07 fix): this used to be a stub that unconditionally
    returned DE_HNDLDSKFULL, on the theory that AH=40h/DosWrite() never
    called it. That stopped being true once case 0x40 was wired up in
    fdos_21h.c: since DE_HNDLDSKFULL != SUCCESS, rwblock() took the "no
    more space" branch on *every* write to a regular file and returned
    0 without transferring any data - CF=0 (success) with AX=0 bytes
    written, i.e. a silent no-op write, not a visible error. Restored
    the real body below (map_cluster() does the actual allocation via
    extend(), which is also fixed in this same patch).

    Migrated from fatfs.c verbatim (WRITEZEROS branch omitted: it is
    not defined in this port, same as upstream default).
*/
STATIC COUNT dos_extend(f_node_ptr fnp, BOOL emptywrite)
{
  if (fnp->f_offset <= fnp->f_dir.dir_size)
    return SUCCESS;

  {
    BOOL special = 0;
    const dpb_ref d(fnp->f_dpb);
    const UWORD secsize = d.dpb_secsize();
    const UBYTE shftcnt = d.dpb_shftcnt();
    if (emptywrite && ((fnp->f_offset & (((ULONG)secsize << shftcnt) - 1)) == 0)) {
      special = 1;
      -- fnp->f_offset;
    }
    if (map_cluster(fnp, XFR_WRITE) != SUCCESS) {
      if (special) ++ fnp->f_offset;
      if (fnp->f_cluster != FREE) {
        /* write size if couldn't satisfy full request,
           but at least one cluster is allocated. */
        fnp->f_dir.dir_size = (((ULONG)fnp->f_cluster_offset + 1) * (ULONG)secsize) << shftcnt;
        merge_file_changes(fnp, FALSE);
      }
      return DE_HNDLDSKFULL;
    }
    if (special) ++ fnp->f_offset;

    return SUCCESS;
  }
}


STATIC void fnode_to_sft(f_node_ptr fnp)
{
  const CLUSTER start_cluster =
      getdstart(fnp->f_dpb, &fnp->f_dir);
  const dos_far_ptr sft_far = idx_to_sft(fnp->f_sft_idx);
  const sft_ref sftp(sft_far);

  sftp.flags(fnp->f_flags);
  sftp.attrib(fnp->f_dir.dir_attrib);
  sftp.write_name(fnp->f_dir.dir_name);
  sftp.time(fnp->f_dir.dir_time);
  sftp.date(fnp->f_dir.dir_date);
  sftp.size(fnp->f_dir.dir_size);
  sftp.start_cluster(start_cluster);
  sftp.dir_index(fnp->f_diridx);
  sftp.dir_sector(fnp->f_dirsector);
  sftp.dcb(fnp->f_dpb);
  sftp.position(fnp->f_offset);
  sftp.current_cluster(fnp->f_cluster);
  sftp.rel_cluster((UWORD)fnp->f_cluster_offset);
#ifdef WITHFAT32
  sftp.rel_cluster_high((UWORD)(fnp->f_cluster_offset >> 16));
#endif
}

STATIC VOID wipe_out_clusters(dos_far_ptr /* -> struct dpb */ x86_dpbp, CLUSTER st);
/*
    shrink_file(fnp) - release every cluster past fnp's current file
    position, for a write that truncates a file mid-stream (the
    "AH=40h, CX=0000h" truncate-at-current-offset idiom).

    CAUTION (2026-07 fix): this used to be a stub that printed a
    PANIC message and spun in "for(;;);" forever. It was unreachable
    while dos_extend() unconditionally failed first (see the fix
    above) - once dos_extend() actually succeeds, any CX=0000h write
    reaches this function, so leaving it as an infinite loop would
    have turned the previous silent no-op bug into a hard hang the
    moment the first bug was fixed. Restored the real body below.

    Migrated from fatfs.c verbatim.
*/
STATIC int shrink_file(f_node_ptr fnp)
{
  ULONG lastoffset = fnp->f_offset;     /* has to be saved */
  CLUSTER last, next, st;
  const UBYTE dpb_unit = dpb_ref(fnp->f_dpb).dpb_unit();
  int ret = DE_ACCESS;

  if (fnp->f_offset)
    fnp->f_offset--;            /* last existing cluster */
  else if (fnp->f_cluster == FREE)
    /* zero offset, 0-byte file: nothing to do ! */
    goto done_success;

  if (map_cluster(fnp, XFR_READ) != SUCCESS)    /* error, don't truncate */
    goto done;

  st = fnp->f_cluster;

  next = next_cluster(fnp->f_dpb, st); /* return nr. of 1st cluster after new end */

  if (next <= 1) /* 1/error or 0/FREE chain points into the void */
    goto done;

  /* Loop from start until either a FREE entry is         */
  /* encountered (due to a damaged file system) or the    */
  /* last cluster is encountered.                         */
  /* zap the FAT pointed to                       */

  if (fnp->f_dir.dir_size == 0) /* file shrinks to size 0 */
  {
    fnp->f_cluster = FREE;
    setdstart(fnp->f_dpb, &fnp->f_dir, FREE); /* file no longer has start cluster */
    last = FREE;
  }
  else
  {
    if (next == LONG_LAST_CLUSTER) /* nothing to do, file already ends here */
      goto done_success;
    last = LONG_LAST_CLUSTER; /* make file end */
  }
  if (link_fat(fnp->f_dpb, st, last) != SUCCESS)
    goto done; /* do not wipe remainder of chain if FAT is broken */

  wipe_out_clusters(fnp->f_dpb, next); /* free clusters after the end */
  /* flush buffers, make sure disk is updated */
  if (!flush_buffers(dpb_unit))
    goto done;

done_success:
  ret = SUCCESS;

done:
  fnp->f_offset = lastoffset;   /* has to be restored */
  return ret;
}

/*
    rwblock(fd, buffer, count, mode) - the core of DosRead()/DosWrite()
    for a regular (non-device) file: transfer "count" bytes between
    "buffer" and the file at fd's current position, advancing it.

    Migrated from fatfs.c.
*/
struct rwblock_workspace
{
  f_node_ptr fnp;
  dos_far_ptr x86_bp;
  dos_far_ptr x86_dpb;
  UBYTE dpb_unit;
  UBYTE dpb_clsmask;
  UWORD dpb_data;
#ifdef WITHFAT32
  ULONG dpb_xdata;
  BOOL dpb_is_fat32;
#endif
  dos_far_ptr x86_buffer;
  ULONG currentblock;
  ULONG startoffset;
  UCOUNT xfr_cnt;
  UCOUNT ret_cnt;
  UCOUNT to_xfer;
  UCOUNT sectors_to_xfer;
  UCOUNT sectors_wanted;
  unsigned secsize;
  unsigned sector;
  unsigned boff;
};

static inline uint32_t buffer_data_linear(dos_far_ptr x86_bp, std::size_t off)
{
  return ((uint32_t)FP_SEG(x86_bp) << 4) + FP_OFF(x86_bp) +
         (uint32_t)offsetof(buffer, b_buffer) + (uint32_t)off;
}

static void buffer_from_guest_linear(dos_far_ptr x86_bp, std::size_t off,
                                     uint32_t src, std::size_t len)
{
  guest_move_block(buffer_data_linear(x86_bp, off), src, len);
}

static void buffer_to_guest_linear(dos_far_ptr x86_bp, std::size_t off,
                                   uint32_t dst, std::size_t len)
{
  guest_move_block(dst, buffer_data_linear(x86_bp, off), len);
}

static long rwblock_worker(COUNT fd, UCOUNT count, int mode,
                           struct rwblock_workspace *work)
{
#define fnp             (work->fnp)
#define x86_bp          (work->x86_bp)
#define x86_dpb         (work->x86_dpb)
#define dpb_unit        (work->dpb_unit)
#define dpb_clsmask     (work->dpb_clsmask)
#define dpb_data        (work->dpb_data)
#ifdef WITHFAT32
#define dpb_xdata       (work->dpb_xdata)
#define dpb_is_fat32    (work->dpb_is_fat32)
#endif
#define x86_buffer      (work->x86_buffer)
#define currentblock    (work->currentblock)
#define startoffset     (work->startoffset)
#define xfr_cnt         (work->xfr_cnt)
#define ret_cnt         (work->ret_cnt)
#define to_xfer         (work->to_xfer)
#define sectors_to_xfer (work->sectors_to_xfer)
#define sectors_wanted  (work->sectors_wanted)
#define secsize         (work->secsize)
#define sector          (work->sector)
#define boff            (work->boff)

  /* This state belongs to the active DOS read/write operation and remains
     live across FAT, cache and device-driver calls.  Keep it on the current
     guest stack instead of the tiny native ARM stack. */
  fnp = sft_to_fnode(fd);
  x86_bp = MK_FP(0, 0);
  xfr_cnt = 0;
  ret_cnt = 0;
  to_xfer = count;
  currentblock = 0;

  x86_buffer = adjust_far_x86(x86_buffer);

  if (mode == XFR_WRITE)
  {
    fnp->f_dir.dir_attrib |= D_ARCHIVE;
    /* mark file as modified and set date not valid any more */
    fnp->f_flags &= ~(SFT_FCLEAN|SFT_FDATE); 
    
    if (dos_extend(fnp, count == 0) != SUCCESS)
    {
      /* ecm: control flow may end up here if CX = 0000h and
                the extending failed to allocate a cluster
                behind the last needed. in this case, our
                return here of 0 happens to be correct and
                indicates the extension succeeded. */
      fnode_to_sft(fnp);
      return 0;
    }
    /* ecm: if CX = 0000h and seek was on a cluster boundary > size,
                the dos_extend call will have allocated one cluster
                too many. this is truncated later without problems.
                but does this aid fragmentation maybe ?
            if CX > 0000h then we want to write to the cluster
                anyway, so extending to the cluster that starts at
                the boundary is desired. */
  }
  
  /* Test that we are really about to do a data transfer. If the  */
  /* count is zero and the mode is XFR_READ, just exit. (Any      */
  /* read with a count of zero is a nop).                         */
  /*                                                              */
  /* A write (mode is XFR_WRITE) is a special case.  It sets the  */
  /* file length to the current length (truncates it).            */
  /*                                                              */
  /* NOTE: doing this up front saves a lot of headaches later.    */

  if (count == 0)
  {
    /* NOTE: doing this up front made a lot of headaches later :-( TE */
    /* FAT allocation has to be extended if necessary              TE */
    /* Now done in dos_extend                                      BO */
    /* remove all the following allocated clusters in shrink_file     */
    if (mode == XFR_WRITE)
    {
      fnp->f_dir.dir_size = fnp->f_offset;
      if (shrink_file(fnp) < 0) /* this is the only call to shrink_file... */
        return DE_ACCESS;
      /* why does empty write -always- truncate to current offset? */
    }
    fnode_to_sft(fnp);
    return 0;
  }

  /* prevent overwriting beginning of file when write exceeds 4GB,
     i.e. when overflow of offset occurs, return error on write   */
  if (fnp->f_offset + count < fnp->f_offset)   /* unsigned overflow */
  {                                                                 
    if (mode == XFR_WRITE)         
    {
      /*  can't extend beyond 4G so return '0 byte written, DISK_FULL */
      return DE_HNDLDSKFULL;
    }
    /* else XFR_READ should end automatically at EOF */
  }               

  /* The variable secsize will be used later.                     */
  x86_dpb = fnp->f_dpb;
  {
    const dpb_ref d(x86_dpb);
    secsize = d.dpb_secsize();
    dpb_unit = d.unit();
    dpb_clsmask = d.cluster_mask();
    dpb_data = d.data_start();
#ifdef WITHFAT32
    dpb_is_fat32 = (d.dpb_fatsize() == 0);
    dpb_xdata = d.xdata_start();
#endif
  }

  /* Do the data transfer. Use block transfer methods so that we  */
  /* can utilize memory management in future DOS-C versions.      */
  while (ret_cnt < count)
  {
    /* Do an EOF test and return whatever was transferred   */
    if (mode == XFR_READ && fnp->f_offset >= fnp->f_dir.dir_size)
    {
      fnode_to_sft(fnp);
      return ret_cnt;
    }

    /* Position the file to the fnode's pointer position. This is   */
    /* done by updating the fnode's cluster, block (sector) and     */
    /* byte offset so that read or write becomes a simple data move */
    /* into or out of the block data buffer.                        */

    /* The more difficult scenario is the (more common)     */
    /* file offset case. Here, we need to take the fnode's  */
    /* offset pointer (f_offset) and translate it into a    */
    /* relative cluster position, cluster block (sector)    */
    /* offset (sector) and byte offset (boff). Once we      */
    /* have this information, we need to translate the      */
    /* relative cluster position into an absolute cluster   */
    /* position (f_cluster). This is unfortunate because it */
    /* requires a linear search through the file's FAT      */
    /* entries.                                              */
    if (map_cluster(fnp, mode) != SUCCESS)
    {
      fnode_to_sft(fnp);
      return ret_cnt;
    }
    if (mode == XFR_WRITE)
    {
      merge_file_changes(fnp, FALSE);   /* /// Added - Ron Cemer */
    }

    /* Compute the block within the cluster and the offset  */
    /* within the block.                                    */
    sector = (UBYTE)(fnp->f_offset / secsize) & dpb_clsmask;
    boff = (UWORD)(fnp->f_offset % secsize);

    currentblock = clus2phys(fnp->f_cluster, x86_dpb) + sector;

    /* see comments above */

    if (boff == 0)              /* complete sectors only */
    {
      startoffset = fnp->f_offset;
      sectors_wanted = to_xfer;

      /* avoid EOF problems */
      if (mode == XFR_READ && to_xfer > fnp->f_dir.dir_size - fnp->f_offset)
        sectors_wanted = (UCOUNT)(fnp->f_dir.dir_size - fnp->f_offset);
      
      sectors_wanted /= secsize;

      if (sectors_wanted == 0)
        goto normal_xfer;

      sectors_to_xfer = dpb_clsmask + 1 - sector;

      sectors_to_xfer = min(sectors_to_xfer, sectors_wanted);

      fnp->f_offset += sectors_to_xfer * secsize;

      while (sectors_to_xfer < sectors_wanted)
      {
        if (map_cluster(fnp, mode) != SUCCESS)
          break;

        {
          ULONG nextblock = clus2phys(fnp->f_cluster, x86_dpb);
          if (nextblock != currentblock + sectors_to_xfer)
          {
            #if 0
            printf("FATJUMP fd=%d off=%lu rel=%lu cl=%lu run=%u blk=%lu nextblk=%lu fat32=%u data=%u xdata=%lu\n",
                   fd, (unsigned long)fnp->f_offset,
                   (unsigned long)fnp->f_cluster_offset,
                   (unsigned long)fnp->f_cluster,
                   (unsigned)sectors_to_xfer,
                   (unsigned long)currentblock,
                   (unsigned long)nextblock,
                   dpb_is_fat32 ? 1u : 0u,
                   (unsigned)dpb_data,
                   (unsigned long)dpb_xdata);
            #endif
            break;
          }
        }

        sectors_to_xfer += dpb_clsmask + 1;

        sectors_to_xfer = min(sectors_to_xfer, sectors_wanted);

        fnp->f_offset = startoffset + sectors_to_xfer * secsize;

      }

      xfr_cnt = sectors_to_xfer * secsize;

      /* avoid caching trouble */

      DeleteBlockInBufferCache(currentblock,
                               currentblock + sectors_to_xfer - 1,
                               dpb_unit, mode);

      if (dskxfer(dpb_unit,
                  currentblock,
                  x86_buffer, sectors_to_xfer,
                  mode == XFR_READ ? DSKREAD : DSKWRITE))
      {
        fnp->f_offset = startoffset;
        fnode_to_sft(fnp);
        return DE_ACCESS;
      }

      goto update_pointers;
    }

    /* normal read: just the old, buffer = sector based read */
  normal_xfer:

    /* Get the block we need from cache                     */
    x86_bp = getblock(currentblock, dpb_unit);

    if (far_is_null(x86_bp))
    {
      fnode_to_sft(fnp);
      return ret_cnt;
    }

    /* transfer a block                                     */
    /* Transfer size as either a full block size, or the    */
    /* requested transfer size, whichever is smaller.       */
    /* Then compare to what is left, since we can transfer  */
    /* a maximum of what is left.                           */
    xfr_cnt = min(to_xfer, secsize - boff);
    if (mode == XFR_READ)
      xfr_cnt = (UWORD) min(xfr_cnt, fnp->f_dir.dir_size - fnp->f_offset);

    /* Копия через guest_lin_*: буфер пользователя может лежать в окне EMS
       (Wolf3D читает VSWAP прямо в замапленный page frame) - данные обязаны
       попасть в АКТИВНУЮ страницу, а не в сырую линейную память (mem.h).
       Полносекторный путь ниже (dskxfer -> INT 13h -> write86) банкуется
       сам по себе. */
    {
      const fdos_guest::buffer_ref b(x86_bp);
      BYTE flag = b.flag();
      if (mode == XFR_WRITE)
      {
        buffer_from_guest_linear(x86_bp, boff, EFFECTIVE(x86_buffer), xfr_cnt);
        flag |= BFR_DIRTY | BFR_VALID;
      }
      else
      {
        buffer_to_guest_linear(x86_bp, boff, EFFECTIVE(x86_buffer), xfr_cnt);
      }

      /* complete buffer transferred ? probably not reused later */
      if (xfr_cnt == BUFFERSIZE ||
          (mode == XFR_READ && fnp->f_offset + xfr_cnt == fnp->f_dir.dir_size))
        flag |= BFR_UNCACHE;
      b.flag(flag);
    }

    /* update pointers and counters                         */
    fnp->f_offset += xfr_cnt;

  update_pointers:
    ret_cnt += xfr_cnt;
    to_xfer -= xfr_cnt;
    x86_buffer = add_far_x86(x86_buffer, xfr_cnt);
    if (mode == XFR_WRITE)
    {
      if (fnp->f_offset > fnp->f_dir.dir_size)
      {
        fnp->f_dir.dir_size = fnp->f_offset;
      }
      merge_file_changes(fnp, FALSE);     /* /// Added - Ron Cemer */
    }
  }
  fnode_to_sft(fnp);
  {
    long result = ret_cnt;
#undef fnp
#undef x86_bp
#undef x86_dpb
#undef dpb_unit
#undef dpb_clsmask
#undef dpb_data
#ifdef WITHFAT32
#undef dpb_xdata
#undef dpb_is_fat32
#endif
#undef x86_buffer
#undef currentblock
#undef startoffset
#undef xfr_cnt
#undef ret_cnt
#undef to_xfer
#undef sectors_to_xfer
#undef sectors_wanted
#undef secsize
#undef sector
#undef boff
    return result;
  }
}

long rwblock(COUNT fd, dos_far_ptr x86_buffer, UCOUNT count, int mode)
{
  struct rwblock_workspace work;

  /* Kernel transient state cannot be kept through a raw pointer into pageable
     guest SS:SP: any FAT/cache/device guest access may remap that page. */
  work.x86_buffer = x86_buffer;
  return rwblock_worker(fd, count, mode, &work);
}

void dos_merge_file_changes(int fd)
{
  merge_file_changes(sft_to_fnode(fd), FALSE);
}

/*
    find_fname(path, attr, fnp) - find the directory entry for "path"
    (full path including filename), with the given attribute mask
    applied the same way DOS's FindFirst does.

    Migrated from fatfs.c verbatim.
*/
int find_fname_ref(fdos_path_ref path, int attr, f_node_ptr fnp)
{
  /* check for leading backslash and open the directory given that */
  /* contains the file given by path.                              */
  if ((fnp = split_path_ref(path, fnp)) == NULL)
    return DE_PATHNOTFND;

  while (dir_read(fnp) == 1)
  {
    BYTE dm_name_pat[FNAME_SIZE + FEXT_SIZE];
    dmatch_read_name_pat(fnp->f_dmp, dm_name_pat);
    if (fcbmatch(fnp->f_dir.dir_name, dm_name_pat)
        && (fnp->f_dir.dir_attrib & ~(D_RDONLY | D_ARCHIVE | attr)) == 0)
    {
      return SUCCESS;
    }
    DM_SET16(fnp->f_dmp, dm_entry, (UWORD)(DM_GET16(fnp->f_dmp, dm_entry) + 1));
  }
  return DE_FILENOTFND;
}

int find_fname(const char *path, int attr, f_node_ptr fnp)
{
  return find_fname_ref(fdos_path_native(path), attr, fnp);
}

/* Open a file given the path. Flags is 0 for read, 1 for write and 2   */
/* for update.                                                          */
/* Returns an long where the high word is a status code and the low     */
/* word is an integer file descriptor or a negative error code          */
/* see DosOpenSft(), dosfns.c for an explanation of the flags bits      */
/* directory opens are allowed here; these are not allowed by DosOpenSft*/

STATIC VOID wipe_out(f_node_ptr fnp);
STATIC int alloc_find_free_ref(f_node_ptr fnp, fdos_path_ref path);
STATIC void init_direntry(struct dirent *dentry, unsigned attrib, CLUSTER cluster, const char *name);

/*
Migrated from fatfs.c verbatim.

    the O_TRUNC and O_CREAT branches below used to
    be deliberate "not implemented yet" stubs returning DE_ACCESS - i.e.
    no DOS program could ever create a new file or truncate an existing
    one (redirection ">", COPY CON, compilers/installers writing output,
    etc. all failed). All the pieces they need - wipe_out(),
    alloc_find_free(), init_direntry(), dir_write() - are already fully
    implemented elsewhere in this file (alloc_find_free() is already
    exercised today by dos_rename()'s "create new entry in other
    directory" path), so this is a straight restore of the upstream
    logic, not new design.
*/
int dos_open_ref(fdos_path_ref path, unsigned flags, unsigned attrib, int fd)
{
  REG f_node_ptr fnp = sft_to_fnode(fd);
  int status = find_fname_ref(path, D_ALL | attrib, fnp);

  /* Check that we don't have a duplicate name, so if we  */
  /* find one, truncate it (O_CREAT).                     */
  if (status == SUCCESS)
  {
    unsigned char dir_attrib = fnp->f_dir.dir_attrib;
    if (flags & O_TRUNC)
    {
      /* The only permissable attribute is archive,   */
      /* check for any other bit set. If it is, give  */
      /* an access error.                             */
      if ((dir_attrib & (D_RDONLY | D_DIR | D_VOLID))
          || (dir_attrib & ~D_ARCHIVE & ~attrib))
        return DE_ACCESS;
      /* Release the existing files FAT and set the   */
      /* length to zero, effectively truncating the   */
      /* file to zero.                                */
      wipe_out(fnp);
      status = S_REPLACED;
    }
    else if (flags & O_OPEN)
    {
      /* force r/o open for FCB if the file is read-only */
      if ((flags & O_FCB) && (dir_attrib & D_RDONLY))
        flags = (flags & ~3) | O_RDONLY;

      /* Check permissions. -- JPP
         (do not allow to open volume labels/directories,
          and do not allow writing to r/o files) */
      if ((dir_attrib & (D_DIR | D_VOLID)) ||
          ((dir_attrib & D_RDONLY) && ((flags & O_ACCMODE) != O_RDONLY)))
        return DE_ACCESS;
      status = S_OPENED;
    }
    else
    {
      return DE_FILEEXISTS;
    }
  }
  else if (status == DE_FILENOTFND && (flags & O_CREAT))
  {
    int ret = alloc_find_free_ref(fnp, path);
    if (ret != SUCCESS)
      return ret;
    status = S_CREATED;
  }
  else
  {
    /* open: If we can't find the file, just return a not    */
    /* found error.                                          */
    return status;
  }

  /* Now change to file                                   */
  fnp->f_sft_idx = fd;
  fnp->f_offset = 0l;
  fnp->f_cluster_offset = 0;

  fnp->f_flags &= ~SFT_FDATE;
  /* use FCLEAN even on replaced/created files: the bit is reset */
  /* if the file is written to later                             */
  fnp->f_flags |= SFT_FCLEAN;
  if (status != S_OPENED)
  {
    BYTE dm_name_pat[FNAME_SIZE + FEXT_SIZE];
    dmatch_read_name_pat(fnp->f_dmp, dm_name_pat);
    init_direntry(&fnp->f_dir, attrib, FREE, dm_name_pat);
    if (!dir_write(fnp))
      return DE_ACCESS;
  }

  merge_file_changes(fnp, status == S_OPENED); /* /// Added - Ron Cemer */
  /* /// Moved from above.  - Ron Cemer */
  fnp->f_cluster = getdstart(fnp->f_dpb, &fnp->f_dir);

  fnode_to_sft(fnp);
  return status;
}

int dos_open(char *path, unsigned flags, unsigned attrib, int fd)
{
  return dos_open_ref(fdos_path_native(path), flags, attrib, fd);
}

/* DosCloseSft() (the real implementation - network redirector close,
   device-driver C_CLOSE request, SHARE deregistration, dos_close())
   is defined further down in this file, after dos_open() - it needs
   sft_to_fnode()/fnode_to_sft()/dos_close(), which aren't defined yet
   at this point. The prototype in proto.h is enough for the
   collect==-1 branch in merge_file_changes() above to compile. */

/*
    DosCloseSft(sft_idx, commitonly) - the real implementation behind
    INT 21h AH=3Eh (close) and the "commit" (AH=68h) call.

    Migrated from dosfns.c. Differences from the original:
      - sftp->sft_dev is a dos_far_ptr here (see sft.h), so
        BinaryCharIO() (which takes a pointer to a dos_far_ptr) is
        called against a local copy of it, the same way
        DeviceOpenSft() above already does; dh_attr is read through
        ARM_PTR(sftp->sft_dev) instead of "sftp->sft_dev->dh_attr"
        directly.
      - the SFT_FSHARED (network redirector) branch is migrated as-is
        but unreachable: SFT_FSHARED can only be set by the IS_NETWORK
        path in DosOpenSft(), which - see its comment - can never be
        taken in this codebase (no redirector exists to create a
        network drive). network_redirector_fp() always reports
        failure (see its definition above) regardless.
      - the SHARE-installed branch (share_close_file()) is left as a
        deliberate panic, same reasoning as DosOpenSft()'s SHARE
        branch above: IsShareInstalled() always returns FALSE, so it
        is unreachable right now, not silently wrong.
*/
COUNT DosCloseSft(int sft_idx, BOOL commitonly)
{
  dos_far_ptr _s = idx_to_sft(sft_idx);
  if (far_is_end(_s))
    return DE_INVLDHNDL;

  const sft_ref sftp(_s);
  fatfs_idata.lp_cur_sft(_s);

  const UWORD flags = sftp.flags();
  if (flags & SFT_FDEVICE)
  {
    const dos_far_ptr devp = sftp.dev();
    if (dhdr_ref(devp).attr() & SFT_FOCRM)
    {
      dos_far_ptr dev = devp;
#if DIAG
      dos_diag_kernel_code = 0x43400000u
                           | (((unsigned)sft_idx & 0xffu) << 16)
                           | ((unsigned)sftp.count() & 0xffffu);
#endif
      if (BinaryCharIO(&dev, 0, MK_FP(0,0), C_CLOSE) != SUCCESS)
        return DE_INVLDHNDL;
#if DIAG
      dos_diag_kernel_code = 0x43500000u
                           | (((unsigned)sft_idx & 0xffu) << 16)
                           | ((unsigned)sftp.count() & 0xffffu);
#endif
    }
    if (!commitonly)
    {
      const UWORD count = sftp.count();
      sftp.count((UWORD)(count - 1u));
    }
    return SUCCESS;
  }

  const int result = dos_close(sft_idx);
  if (commitonly || result != SUCCESS)
    return result;

  if (sftp.count() == 1 && IsShareInstalled(TRUE))
  {
    const WORD shroff = sftp.shroff();
    if (shroff >= 0)
      share_close_file(shroff);
    sftp.shroff(-1);
  }

  {
    const UWORD count = sftp.count();
    sftp.count((UWORD)(count - 1u));
  }
  return SUCCESS;
}

/*
    DosClose(hndl) - INT 21h AH=3Eh: close a DOS file handle for the
    current process.

    Migrated from dosfns.c. PSP/JFT state is accessed through psp_ref so
    pageable guest RAM is never exposed as a native pointer here.
*/
COUNT DosClose(COUNT hndl)
{
  const psp_ref process(fatfs_idata.cu_psp());
  int sft_idx = get_sft_idx(hndl);
#if DIAG
  dos_diag_kernel_code = 0x43100000u
                       | (((unsigned)sft_idx & 0xffu) << 16)
                       | ((unsigned)hndl & 0xffffu);
#endif
  dos_far_ptr /* -> sft */ s = idx_to_sft(sft_idx);
  if (far_is_end(s))
    return DE_INVLDHNDL;
  const dos_far_ptr table = process.file_table();
  if (far_is_null(table) || far_is_end(table) || hndl >= process.max_files())
    return DE_INVLDHNDL;
  /* We must close the (valid) file handle before any critical error */
  /* may occur, else e.g. ABORT will try to close the file twice,    */
  /* the second time after stdout is already closed */
  pstore8(((uint32_t)FP_SEG(table) << 4) + FP_OFF(table) + (UWORD)hndl, 0xff);
#if DIAG
  dos_diag_kernel_code = 0x43200000u
                       | (((unsigned)sft_idx & 0xffu) << 16)
                       | ((unsigned)hndl & 0xffffu);
#endif
  /* Get the SFT block that contains the SFT      */
  {
    COUNT rc = DosCloseSft(sft_idx, FALSE);
#if DIAG
    dos_diag_kernel_code = 0x43300000u
                         | (((unsigned)sft_idx & 0xffu) << 16)
                         | ((unsigned)hndl & 0xffffu);
#endif
    return rc;
  }
}

/*                                                                      */
/* split a path into it's component directory and file name             */
/*                                                                      */
/*
    Migrated from fatfs.c. The DEBUG-only redirected-drive check reads
    CDS flags through cds_ref because get_cds() returns a guest far pointer.
*/
f_node_ptr split_path_ref(fdos_path_ref path, f_node_ptr fnp)
{
  const size_t len = fdos_path_len(path, FDOS_PATHLEN);
  /* check if the path ends in a backslash                        */
  if (len == 0 || fdos_path_get(path, len - 1u) == '\\')
    return (f_node_ptr) 0;

/*  11/29/99 jt
   * Networking and Cdroms. You can put in here a return.
   * Maybe a return of 0xDEADBEEF or something for Split or Dir_open.
   * Just to let upper level Fdos know its a sft, CDS function.
   * Right now for Networking there is no support for Rename, MkDir
   * RmDir & Delete.

   <insert code here or in dir_open. I would but it in Dir_open.
   Do the redirection in Network.c>

 */
#ifdef DEBUG
  if (cds_ref(get_cds((COUNT)fdos_path_get(path, 0)-'A')).flags() & CDSNETWDRV)
  {
    printf("split path called for redirected file\n");
    return (f_node_ptr) 0;
  }
#endif

  /* Translate the path into a useful pointer                     */
  return dir_open_ref(path, TRUE, fnp);
}

f_node_ptr split_path(const char *path, f_node_ptr fnp)
{
  return split_path_ref(fdos_path_native(path), fnp);
}

/*
    dir_exists(path) - true if "path" names an existing directory.

    Migrated from fatfs.c verbatim.
*/
BOOL dir_exists(char * path)
{
  return split_path(path, fnode_slot(0)) != NULL;
}

/*
    dos_cd(PathName) - change the current directory (the part of
    CHDIR that updates the CDS once the new directory has been
    confirmed to exist).

    Migrated from fatfs.c. get_cds() returns a guest far pointer here,
    so the CDS start-cluster update goes through cds_ref.
*/
int dos_cd_ref(fdos_path_ref PathName)
{
  f_node_ptr fnp;
  /* now test for its existance. If it doesn't, return an error.  */
  if ((fnp = dir_open_ref(PathName, FALSE, fnode_slot(0))) == NULL)
    return DE_PATHNOTFND;

  /* problem: RBIL table 01643 does not give a FAT32 field for the
     CDS start cluster. But we are not using this field ourselves */
  {
    dos_far_ptr /* -> struct cds */ x86_cdsp = get_cds((COUNT)fdos_path_get(PathName, 0) - 'A');

    /* get_cds() reports "no such drive" as the 0000:0000 sentinel, and
       ARM_PTR() resolves that to X86_RAM_BASE + 0 - the guest's interrupt
       vector table (see the note in cds.h). Upstream gets away with the
       unchecked write because there a NULL far pointer is simply unmapped;
       here it would silently rewrite an interrupt vector. truename() has
       already validated the drive letter by the time dos_cd() is reached,
       so this is belt-and-braces - but it is the difference between a
       broken precondition being harmless and it taking down the system. */
    if (!far_is_null(x86_cdsp))
      cds_ref(x86_cdsp).start_cluster((UWORD)DM_GET32(fnp->f_dmp, dm_dircluster));
  }
  return SUCCESS;
}

int dos_cd(char *PathName)
{
  return dos_cd_ref(fdos_path_native(PathName));
}


/*
    get_dpb(dsk) - return a pointer to the DPB for logical drive "dsk"
    (0=A:, 1=B:, ...), or NULL if the drive isn't a valid, non-network
    drive.

    Migrated from fatfs.c.
*/
dos_far_ptr/*struct dpb*/ get_dpb(COUNT dsk)
{
  dos_far_ptr x86_cdsp = get_cds(dsk);

  if (far_is_null(x86_cdsp))
    return x86_cdsp;

  const cds_ref cdsp(x86_cdsp);
  if (cdsp.flags() & CDSNETWDRV)
    return MK_FP(0, 0);
  return cdsp.dpb();
}

STATIC int rqblockio(unsigned char command, dos_far_ptr/*struct dpb*/ _dpbp)
{
  const dpb_ref d(_dpbp);
 retry:
  media_req.length(sizeof(request));
  media_req.unit(d.dpb_subunit());
  media_req.command(command);
  media_req.mcmdesc(d.dpb_mdb());
  media_req.status(0);
  if (command == C_BLDBPB)
    media_req.bpfat(DiskTransferBuffer);

  drv_watch_set_dpb_context(_dpbp, command, d.dpb_unit(),
                            d.dpb_subunit(), media_check_source);

  dpb_watch_check("rqblockio-before-execrh", _dpbp);
  execrh(media_req_far, d.device());
  dpb_watch_check("rqblockio-after-execrh", _dpbp);
  UWORD status = media_req.status();
  if ((status & S_ERROR) || !(status & S_DONE))
  {
    if ((status & (S_ERROR | S_MASK)) == (S_ERROR | E_NOTRDY))
      return DE_INVLDDRV;

    FOREVER
    {
      switch (block_error_status(status, d.dpb_unit(), d.device(), 0))
      {
      case ABORT:
      case FAIL:
        return DE_INVLDDRV;

      case RETRY:
        goto retry;

      case CONTINUE:
        return SUCCESS;
      }
    }
  }
  return SUCCESS;
}

#ifdef WITHFAT32
VOID bpb_to_dpb(dos_far_ptr bp, dos_far_ptr dp, BOOL extended)
#else
VOID bpb_to_dpb(dos_far_ptr bp, dos_far_ptr dp)
#endif
{
  const bpb_ref b(bp);
  const dpb_ref d(dp);
  const UBYTE nsector = b.bpb_nsector();
  UWORD shftcnt;
  if (nsector == 0) shftcnt = 8;
  else for (shftcnt = 0; (nsector >> shftcnt) > 1; ++shftcnt) {}

  const UWORD secsize = b.bpb_nbyte();
  const UWORD fatstrt = b.bpb_nreserved();
  const UBYTE fats = b.bpb_nfat();
  const UWORD fatsize = b.bpb_nfsect();
  const UWORD dirents = b.bpb_ndirent();
  const UWORD dirstrt = (UWORD)(fatstrt + fats * fatsize);
  const UWORD data = (UWORD)(dirstrt + (dirents + secsize / DIRENT_SIZE - 1) / (secsize / DIRENT_SIZE));
  const ULONG size = b.bpb_nsize() == 0 ? b.bpb_huge() : (ULONG)b.bpb_nsize();
  UWORD clusters = (UWORD)(((size - data) >> shftcnt) + 1u);

  {
    unsigned fatsiz;
    const ULONG tmp = fatsize * (ULONG)(secsize / 2u);
    if (tmp < 0x10000UL) {
      fatsiz = (unsigned)tmp;
      if (clusters > FAT_MAGIC) {
        if (fatsiz > FAT_MAGIC && clusters >= fatsiz) clusters = (UWORD)(fatsiz - 1u);
      } else if (fatsiz < 0x4000u) {
        fatsiz = fatsiz * 4u / 3u;
        if (clusters >= fatsiz) clusters = (UWORD)(fatsiz - 1u);
      }
    }
  }

  d.dpb_shftcnt((UBYTE)shftcnt);
  d.dpb_mdb(b.bpb_mdesc()); d.dpb_secsize(secsize);
  d.dpb_clsmask((UBYTE)((nsector - 1u) & 0xffu)); d.dpb_fatstrt(fatstrt);
  d.dpb_fats(fats); d.dpb_dirents(dirents); d.dpb_fatsize(fatsize);
  d.dpb_dirstrt(dirstrt); d.dpb_data(data); d.dpb_size(clusters);
  d.flags(0); d.cluster(UNKNCLUSTER); d.nfree(UNKNCLSTFREE);
#ifdef WITHFAT32
  if (extended) {
    const ULONG xfatsize = fatsize == 0 ? b.bpb_xnfsect() : fatsize;
    d.dpb_xfatsize(xfatsize); d.dpb_xcluster(UNKNCLUSTER); d.xnfree(XUNKNCLSTFREE);
    d.dpb_xflags(0); d.dpb_xfsinfosec(0xffff); d.dpb_xbackupsec(0xffff);
    d.dpb_xrootclst(0); d.dpb_xdata(data); d.dpb_xsize(clusters);
    if (d.dpb_fatsize() == 0) {
      d.dpb_xflags(b.bpb_xflags()); d.dpb_xfsinfosec(b.bpb_xfsinfosec());
      d.dpb_xbackupsec(b.bpb_xbackupsec()); d.dpb_dirents(0); d.dpb_dirstrt(0xffff);
      d.dpb_size(0);
      const ULONG xdata = fatstrt + (ULONG)fats * xfatsize;
      d.dpb_xdata(xdata); d.dpb_xsize(((size - xdata) >> shftcnt) + 1u);
      d.dpb_xrootclst(b.bpb_xrootclst()); read_fsinfo(dp);
    }
  }
#endif
}

/*
    dos_free(dpbp) - free cluster count for the drive.
    Ported verbatim from the original kernel (fatfs.c). Returns the
    cached dpb_(x)nfreeclst when valid, otherwise walks the FAT via
    is_free_cluster() (read-only path already migrated in fattab.c),
    caches the result and, for FAT32, persists it through
    write_fsinfo(). Needed by DosGetFree() (INT 21h AH=36h) and
    FatGetDrvData() (AH=1Bh/1Ch).
*/
CLUSTER dos_free(dos_far_ptr /* -> struct dpb */ x86_dpbp)
{
  const dpb_ref d(x86_dpbp);
  /* There's an unwritten rule here. All fs       */
  /* cluster start at 2 and run to max_cluster+2  */
  REG CLUSTER i;
  REG CLUSTER cnt;
  CLUSTER max_cluster = d.dpb_size();
#ifdef WITHFAT32
  const BOOL is_fat32 = (d.dpb_fatsize() == 0);
  if (is_fat32)
  {
    const ULONG nfree = d.xnfree();
    if (nfree != XUNKNCLSTFREE)
      return nfree;
    max_cluster = d.dpb_xsize();
  }
  else
#endif
  if (d.nfree() != UNKNCLSTFREE)
    return d.nfree();

  cnt = 0;
  for (i = 2; i <= max_cluster; i++)
  {
    if (is_free_cluster(x86_dpbp, i))
    {
      if (cnt == 0)
      {
        /* update first free cluster number */
#ifdef WITHFAT32
        if (is_fat32)
          d.dpb_xcluster(i);
        else
#endif
          d.cluster((UWORD)i);
      }
      ++cnt;
    }
  }
#ifdef WITHFAT32
  if (is_fat32)
  {
    d.xnfree(cnt);
    write_fsinfo(x86_dpbp);
    return cnt;
  }
#endif
  d.nfree((UWORD)cnt);
  return cnt;
}

/*
    media_check(dpbp) - check whether removable media in drive dpbp
    may have been swapped since the last access, and if so, rebuild
    the DPB's BPB-derived fields from the new media.
*/
COUNT media_check_tagged(dos_far_ptr /*struct dpb*/ _dpbp, const char *source)
{
  media_check_source = source;
  if (far_is_null(_dpbp))
    return DE_INVLDDRV;
  dpb_watch_check("media_check-entry", _dpbp);

  int ret = rqblockio(C_MEDIACHK, _dpbp);
  dpb_watch_check("media_check-after-C_MEDIACHK", _dpbp);
  if (ret < SUCCESS)
    return ret;

  const dpb_ref d(_dpbp);
  const UBYTE unit = d.dpb_unit();
  dpb_watch_check("media_check-before-switch", _dpbp);
  switch (media_req.mcretcode() | d.flags())
  {
    case M_NOT_CHANGED:
      dpb_watch_check("media_check-case-not-changed", _dpbp);
      return SUCCESS;

    case M_DONT_KNOW:
      dpb_watch_check("media_check-case-dont-know", _dpbp);
      if (dirty_buffers(unit)) {
        dpb_watch_check("media_check-after-dirty_buffers", _dpbp);
        return SUCCESS;
      }
      dpb_watch_check("media_check-after-dirty_buffers2", _dpbp);
      __attribute__((fallthrough));
    default:
      dpb_watch_check("media_check-case-default-before-setinvld", _dpbp);
      setinvld(unit);
      dpb_watch_check("media_check-after-setinvld", _dpbp);
      ret = rqblockio(C_BLDBPB, _dpbp);
      dpb_watch_check("media_check-after-C_BLDBPB", _dpbp);
      if (ret < SUCCESS)
        return ret;
      {
        const dos_far_ptr bpbp = media_req.bpptr();
#ifdef WITHFAT32
        bpb_to_dpb(bpbp, _dpbp, bpb_ref(bpbp).bpb_nfsect() == 0);
#else
        bpb_to_dpb(bpbp, _dpbp);
#endif
      }
      dpb_watch_check("media_check-after-bpb_to_dpb", _dpbp);
      return SUCCESS;
  }
}
COUNT media_check(dos_far_ptr /*struct dpb*/ _dpbp)
{
  return media_check_tagged(_dpbp, "media_check");
}
/*    clus2phys(cl_no, dpbp) - convert a cluster number into the absolute
    sector number of its first sector.

    The DPB stays in guest memory; read only the scalar geometry fields
    needed for the conversion.
*/
ULONG clus2phys(CLUSTER cl_no, dos_far_ptr x86_dpbp)
{
  const dpb_ref d(x86_dpbp);
  ULONG data = d.dpb_data();
#ifdef WITHFAT32
  if (d.dpb_fatsize() == 0)
    data = d.dpb_xdata();
#endif
  return ((ULONG)(cl_no - 2) << d.dpb_shftcnt()) + data;
}

/*
    getdstart(dpbp)/setdstart(dpbp, dentry, value) - get/set a
    directory entry's starting cluster number, taking the FAT32
    high-word split (dir_start + dir_start_high) into account when the
    volume is FAT32.

    Migrated from fatfs.c verbatim.
*/
CLUSTER getdstart(dos_far_ptr x86_dpbp, struct dirent *dentry)
{
  const dpb_ref d(x86_dpbp);
#ifdef WITHFAT32
  if (d.dpb_fatsize() == 0)
    return (((CLUSTER)dentry->dir_start_high << 16) | dentry->dir_start);
#endif
  return dentry->dir_start;
}

void setdstart(dos_far_ptr x86_dpbp, struct dirent *dentry, CLUSTER value)
{
  const dpb_ref d(x86_dpbp);
  dentry->dir_start = (UWORD)value;
#ifdef WITHFAT32
  if (d.dpb_fatsize() == 0)
    dentry->dir_start_high = (UWORD)(value >> 16);
#endif
}

STATIC CLUSTER find_fat_free(f_node_ptr fnp);
/*
    extend(fnp) - extend a directory or file by exactly one cluster.
    Only map_cluster() calls this in a loop (for files); dos_mkdir()/
    extend_dir() call it once each (for directories).

    CAUTION (2026-07 fix): this used to be a stub returning
    LONG_LAST_CLUSTER unconditionally, i.e. "disk full" every time.
    That silently broke every caller above it that was otherwise
    already fully migrated and working (map_cluster() -> any write
    that needs to grow a file; extend_dir()/dos_mkdir() -> MKDIR).
    find_fat_free(), link_fat(), next_cluster() and setdstart(), which
    this function is built on, are all already real (verbatim)
    migrations - only the glue between them was missing.

    Migrated from fatfs.c verbatim (put_string() -> printf(), same
    convention already used by clusterMessage() in fattab.c: this is a
    "run chkdsk" diagnostic for a corrupt FAT chain, not guest-visible
    output, and put_string() itself is not implemented in this port).
*/
STATIC CLUSTER extend(f_node_ptr fnp)
{
  CLUSTER free_fat;

  /* get an empty cluster, so that we use it to extend the file.  */
  free_fat = find_fat_free(fnp);

  /* No empty clusters, disk is FULL! Translate into a useful     */
  /* error message.                                               */
  if (free_fat == LONG_LAST_CLUSTER)
    return free_fat;

  /* if 1a or 1b works but 2 fails, we get a pointer into an wrong FAT entry */
  /* our new fattab.c checks should be able to trap the bad pointers for now */
  if (link_fat(fnp->f_dpb, free_fat, LONG_LAST_CLUSTER) != SUCCESS) /* 2 */ /* free->last */
      return LONG_LAST_CLUSTER; /* do not try 1a/1b if 2 did not work out */
  /* if 2 works but 1a/1b fails, we only get a harmless lost cluster here */

  /* Now that we have found a free FAT entry, mark it as the last entry of */
  /* the chain and save (note: BUFFERS cause nondeterministic write order) */
  if (fnp->f_cluster == FREE) /* if the file leaves the empty state */
    setdstart(fnp->f_dpb, &fnp->f_dir, free_fat); /* 1a */
  else
  {
    /* let previously last chain element chain to newly allocated cluster! */
    if (next_cluster(fnp->f_dpb, fnp->f_cluster) != LONG_LAST_CLUSTER)
    {
      /* we tried to "grow a file in the middle", f_node or FAT messed up? */
      printf("FAT chain size bad!\n");
      return LONG_LAST_CLUSTER;
    }
    if (link_fat(fnp->f_dpb, fnp->f_cluster, free_fat) != SUCCESS) /* 1b */ /* last->used */
      return LONG_LAST_CLUSTER; /* should never happen */
  }

  return free_fat;
}

/* Description.
 *    Finds the cluster which contains byte at the fnp->f_offset offset and
 *  stores its number to the fnp->f_cluster. The search begins from the start of
 *  a file or a directory depending on whether the SFT index is valid
 *  and continues through the FAT chain until the target cluster is found.
 *  The mode can have only XFR_READ or XFR_WRITE values.
 *    In the XFR_WRITE mode map_cluster extends the FAT chain by creating
 *  new clusters upon necessity.
 * Return value.
 *  DE_HNDLDSKFULL - [XFR_WRITE mode only] unable to find free cluster
 *                   for extending the FAT chain, the disk is full.
 *                   The fnode is released from memory.
 *  DE_SEEK        - [XFR_READ mode only] byte at f_offset lies outside of
 *                   the FAT chain. The fnode is not released.
 * Notes.
 *  If we are moving forward, then use the relative cluster number offset
 *  that we are at now (f_cluster_offset) to start, instead of starting
 *  at the beginning.

    Migrated from fatfs.c verbatim.
*/
COUNT map_cluster(REG f_node_ptr fnp, COUNT mode)
{
  CLUSTER relcluster, cluster;

  if (fnp->f_cluster == FREE)
  {
    /* If this is a read but the file still has zero bytes return   */
    /* immediately....                                              */
    if (mode == XFR_READ)
      return DE_SEEK;

    /* If someone did a seek, but no writes have occured, we will   */
    /* need to initialize the fnode.                                */
    /*  (mode == XFR_WRITE) */
    /* If there are no more free fat entries, then we are full! */
    cluster = extend(fnp);
    if (cluster == LONG_LAST_CLUSTER)
    {
      return DE_HNDLDSKFULL;
    }
    fnp->f_cluster = cluster;
  }

  const dpb_ref dpb(fnp->f_dpb);
  const UWORD dpb_secsize = dpb.dpb_secsize();
  const UBYTE dpb_shftcnt = dpb.dpb_shftcnt();
  relcluster = (CLUSTER)((fnp->f_offset / dpb_secsize) >> dpb_shftcnt);

  if (relcluster < fnp->f_cluster_offset)
  {
    /* If seek is to earlier in file than current position, */
    /* we have to follow chain from the beginning again...  */
    /* Set internal index and cluster size.                 */
    fnp->f_cluster = fnp->f_sft_idx == 0xff ? DM_GET32(fnp->f_dmp, dm_dircluster) :
        getdstart(fnp->f_dpb, &fnp->f_dir);
    fnp->f_cluster_offset = 0;
  }

  /* Now begin the linear search. The relative cluster is         */
  /* maintained as part of the set of physical indices. It is     */
  /* also the highest order index and is mapped directly into     */
  /* physical cluster. Our search is performed by pacing an index */
  /* up to the relative cluster position where the index falls    */
  /* within the cluster.                                          */

  while (fnp->f_cluster_offset != relcluster)
  {
    /* get next cluster in the chain */
    cluster = next_cluster(fnp->f_dpb, fnp->f_cluster);
    #if 0
    if (relcluster == 1)
      dos_printf("FATMAP fd=%u off=%lu rel=%lu saved=%lu cur=%lu next=%lu xsize=%lu spc=%u\r\n",
                 (unsigned)fnp->f_sft_idx, (unsigned long)fnp->f_offset,
                 (unsigned long)relcluster, (unsigned long)fnp->f_cluster_offset,
                 (unsigned long)fnp->f_cluster, (unsigned long)cluster,
                 (unsigned long)f_dpb->dpb_xsize,
                 (unsigned)(f_dpb->dpb_clsmask + 1));
    #endif
/*
    printf("map_cluster next off=%lu size=%lu rel=%lu cur=%lu next=%lu dpb_size=%u phys=%lu\n",
           fnp->f_offset, fnp->f_dir.dir_size,
           (unsigned long)relcluster,
           (unsigned long)fnp->f_cluster,
           (unsigned long)cluster,
           fnp->f_dpb->dpb_size,
           cluster >= 2 && cluster <= fnp->f_dpb->dpb_size
             ? clus2phys(cluster, fnp->f_dpb) : 0UL);
*/
    if (cluster <= 1) /* 1/error or 0/FREE chain into the void */
    {
      #if 0
      if (mode == XFR_READ)
        printf("FATFAIL fd=%u off=%lu rel=%lu saved=%lu cur=%lu next=%lu reason=invalid\n",
               (unsigned)fnp->f_sft_idx, (unsigned long)fnp->f_offset,
               (unsigned long)relcluster, (unsigned long)fnp->f_cluster_offset,
               (unsigned long)fnp->f_cluster, (unsigned long)cluster);
      #endif
      return DE_SEEK;
    }

    /* If this is a read and the next is a LAST_CLUSTER,               */
    /* then we are going to read past EOF, return zero read            */
    /* or expand the list if we're going to write and have run into    */
    /* the last cluster marker.                                        */
    if (cluster == LONG_LAST_CLUSTER)
    {
      if (mode == XFR_READ)
      {
        #if 0
        printf("FATFAIL fd=%u off=%lu rel=%lu saved=%lu cur=%lu next=%lu reason=eoc\n",
               (unsigned)fnp->f_sft_idx, (unsigned long)fnp->f_offset,
               (unsigned long)relcluster, (unsigned long)fnp->f_cluster_offset,
               (unsigned long)fnp->f_cluster, (unsigned long)cluster);
        #endif
        return DE_SEEK;
      }

      /* mode == XFR_WRITE */
      cluster = extend(fnp);
      if (cluster == LONG_LAST_CLUSTER)
        return DE_HNDLDSKFULL;
    }

    fnp->f_cluster = cluster;
    fnp->f_cluster_offset++;
  }

  return SUCCESS;
}

/*
    fcbmatch(fcbname1, fcbname2) - compare two FCB-style (8.3,
    space-padded, no dot) names for an exact match.

    Migrated from fatfs.c verbatim.
*/
BOOL fcbmatch(const char *fcbname1, const char *fcbname2)
{
  return memcmp(fcbname1, fcbname2, FNAME_SIZE + FEXT_SIZE) == 0;
}

/* Description.
 *  Remove entries with D_LFN attribute preceeding the directory entry
 *  pointed by fnp, fnode isn't modified (I hope).
 * Return value. 
 *  SUCCESS     - completed successfully.
 *  DE_ACCESS   - error occurred, fnode is released.
 * input: fnp with valid non-LFN directory entry, not equal to '..' or
 *  '.'
 */
COUNT remove_lfn_entries(f_node_ptr fnp)
{
  unsigned original_diroff = DM_GET16(fnp->f_dmp, dm_entry);

  while (TRUE)
  {
    if (DM_GET16(fnp->f_dmp, dm_entry) == 0)
      break;
    DM_SET16(fnp->f_dmp, dm_entry, (UWORD)(DM_GET16(fnp->f_dmp, dm_entry) - 1));
    if (dir_read(fnp) <= 0)
      return DE_ACCESS;
    if (fnp->f_dir.dir_attrib != D_LFN)
      break;
    fnp->f_dir.dir_name[0] = DELETED;
    if (!dir_write(fnp)) return DE_ACCESS;
  }
  DM_SET16(fnp->f_dmp, dm_entry, (UWORD)original_diroff);
  if (dir_read(fnp) <= 0)
    return DE_ACCESS;

  return SUCCESS;
}

STATIC BOOL find_free(f_node_ptr fnp)
{
  COUNT rc;

  while ((rc = dir_read(fnp)) == 1)
  {
    if (fnp->f_dir.dir_name[0] == DELETED)
      return TRUE;
    DM_SET16(fnp->f_dmp, dm_entry, (UWORD)(DM_GET16(fnp->f_dmp, dm_entry) + 1));
  }
  return rc >= 0;
}

/* clear out the blocks in the cluster for a directory */
STATIC int clear_dir(f_node_ptr fnp, CLUSTER cluster)
{
  const dpb_ref d(fnp->f_dpb);
  const UBYTE clsmask = d.dpb_clsmask();
  const UBYTE unit = d.dpb_unit();
  const UBYTE shftcnt = d.dpb_shftcnt();
  ULONG data = d.dpb_data();
#ifdef WITHFAT32
  if (d.dpb_fatsize() == 0)
    data = d.dpb_xdata();
#endif
  const ULONG first_sector = ((ULONG)(cluster - 2) << shftcnt) + data;

  for (int idx = 0; idx <= clsmask; idx++)
  {
    /* as we are overwriting it completely, don't read first */
    const dos_far_ptr x86_bp = getblockOver(first_sector + idx, unit);
#ifdef DISPLAY_GETBLOCK
    printf("DIR (clear_dir)\n");
#endif
    if (far_is_null(x86_bp))
      return DE_ACCESS;
    const fdos_guest::buffer_ref b(x86_bp);
    b.fill_data(0, 0, BUFFERSIZE);
    BYTE flag = static_cast<BYTE>(b.flag() | BFR_DIRTY | BFR_VALID);
    if (idx != 0)
      flag |= BFR_UNCACHE;              /* needs not be cached */
    b.flag(flag);
  }
  return SUCCESS;
}

COUNT extend_dir(f_node_ptr fnp)
{
  int ret;
  CLUSTER cluster = extend(fnp);
  if (cluster == LONG_LAST_CLUSTER)
    return DE_HNDLDSKFULL;

  ret = clear_dir(fnp, cluster);
  if (ret != SUCCESS)
    return ret;

  if (!find_free(fnp))
    return DE_HNDLDSKFULL;

  /* flush the drive buffers so that all info is written          */
  if (!flush_buffers(dpb_ref(fnp->f_dpb).dpb_unit()))
    return DE_ACCESS;

  return SUCCESS;

}

/* alloc_find_free: resets the directory                          */
/* Then finds a spare directory entry and if not                  */
/* available, tries to extend the directory.                      */
STATIC int alloc_find_free_ref(f_node_ptr fnp, fdos_path_ref path)
{
  fnp = split_path_ref(path, fnp);

  /* Get a free f_node pointer so that we can use */
  /* it in building the new file.                 */
  /* Note that if we're in the root and we don't  */
  /* find an empty slot, we need to abort.        */
  if (find_free(fnp) == 0)
  {
    if (DM_GET32(fnp->f_dmp, dm_dircluster) == 0)
    {
      return DE_TOOMANY;
    }
    else
    {
      /* Otherwise just expand the directory          */
      int ret;

      if ((ret = extend_dir(fnp)) != SUCCESS)
        /* fnp already closed in extend_dir */
        return ret;
    }
  }
  return SUCCESS;
}

COUNT dos_rename_ref(fdos_path_ref path1, fdos_path_ref path2, int attrib)
{
  REG f_node_ptr fnp1;
  REG f_node_ptr fnp2;
  COUNT ret;
  char *fcbname;

  /* prevent renaming of the current directory of that drive */
  dos_far_ptr /* -> struct cds */ _cds = get_cds((COUNT)fdos_path_get(path1, 0) - 'A');
  if (cds_current_path_equals_ref(_cds, path1))
    return DE_RMVCUDIR;

  /* first check if the source file exists                        */
  fnp1 = fnode_slot(0);
  ret = find_fname_ref(path1, attrib, fnp1);
  if (ret != SUCCESS)
    return ret;

  /* Check that we don't have a duplicate name, so if we find     */
  /* one, it's an error.                                          */
  fnp2 = fnode_slot(1);
  ret = find_fname_ref(path2, attrib, fnp2);
  if (ret != DE_FILENOTFND)
    return ret == SUCCESS ? DE_ACCESS : ret;

  BYTE fcbname_buf[FNAME_SIZE + FEXT_SIZE];
  dmatch_read_name_pat(fnp2->f_dmp, fcbname_buf);
  fcbname = fcbname_buf;
  if (DM_GET32(fnp1->f_dmp, dm_dircluster) == DM_GET32(fnp2->f_dmp, dm_dircluster))
  {
    /* rename in the same directory: change the directory entry in-place */
    fnp2 = fnp1;
    if ((ret = remove_lfn_entries(fnp1)) < 0)
      return ret;
  }
  else
  {
    /* do not allow to rename directories between different directories  */
    if (fnp1->f_dir.dir_attrib & D_DIR)
      return DE_ACCESS;

    /* create new entry in other directory */
    ret = alloc_find_free_ref(fnp2, path2);
    if (ret != SUCCESS)
      return ret;

    if ((ret = remove_lfn_entries(fnp1)) < 0)
      return ret;

    /* init fnode for new file name to match old file name */
    dos_api_memcpy(&fnp2->f_dir, &fnp1->f_dir, sizeof(struct dirent));

    /* Ok, so we can delete this one. Save the file info.           */
    *(fnp1->f_dir.dir_name) = DELETED;

    if (!dir_write(fnp1))
      return DE_ACCESS;
  }

  /* put the fnode's name into the directory.                     */
  dos_api_memcpy(fnp2->f_dir.dir_name, fcbname, FNAME_SIZE + FEXT_SIZE);

  /* SUCCESSful completion, return it                             */
  return dir_write(fnp2) ? SUCCESS : DE_ACCESS;
}

COUNT dos_rename(BYTE *path1, BYTE *path2, int attrib)
{
  return dos_rename_ref(fdos_path_native((const char *)path1),
                        fdos_path_native((const char *)path2), attrib);
}

COUNT dos_getfattr_ref(fdos_path_ref name)
{
  f_node_ptr fnp = fnode_slot(0);
  int ret = find_fname_ref(name, D_ALL, fnp);
  return ret == SUCCESS ? fnp->f_dir.dir_attrib : ret;
}

COUNT dos_getfattr(BYTE *name)
{
  return dos_getfattr_ref(fdos_path_native((const char *)name));
}

COUNT dos_setfattr_ref(fdos_path_ref name, UWORD attrp)
{
  f_node_ptr fnp;
  int rc;

  /* JPP-If user tries to set VOLID or RESERVED bits, return error.
     We used to also check for D_DIR here, but causes issues with deltree
     which is trying to work around another issue.  So now we check
     these here, and only report DE_ACCESS if user tries to set directory
     bit on a non-directory entry.
   */
  if ((attrp & (D_VOLID | 0xC0)) != 0)
    return DE_ACCESS;

  fnp = fnode_slot(0);
  rc = find_fname_ref(name, D_ALL, fnp);
  if (rc != SUCCESS)
    return rc;

  /* if caller tries to set DIR on non-directory, return error */
  if ((attrp & D_DIR) && !(fnp->f_dir.dir_attrib & D_DIR))
    return DE_ACCESS;

  /* Set the attribute from the fnode and return          */
  /* clear all attributes but DIR and VOLID */
  fnp->f_dir.dir_attrib &= (D_VOLID | D_DIR);   /* JPP */

  /* set attributes that user requested */
  fnp->f_dir.dir_attrib |= attrp;       /* JPP */

  /* close open files in compat mode, otherwise there was a critical error */
  rc = merge_file_changes(fnp, -1);
  if (rc == SUCCESS && !dir_write(fnp))
    rc = DE_ACCESS;
  return rc;
}

/*                                                              */
/* Find free cluster in disk FAT table                          */
/*                                                              */
STATIC CLUSTER find_fat_free(f_node_ptr fnp)
{
  REG CLUSTER idx, size, cluster;
  const dpb_ref d(fnp->f_dpb);
#ifdef WITHFAT32
  const BOOL is_fat32 = (d.dpb_fatsize() == 0);
#endif

#ifdef DISPLAY_GETBLOCK
  printf("[find_fat_free]\n");
#endif

  /* Start from optimized lookup point for start of FAT   */
  idx = 2;
  size = d.dpb_size();

#ifdef WITHFAT32
  if (is_fat32)
  {
    if (d.dpb_xcluster() != UNKNCLUSTER)
      idx = d.dpb_xcluster();
    size = d.dpb_xsize();
  }
  else
#endif
  if (d.cluster() != UNKNCLUSTER)
    idx = d.cluster();

  /* Search the FAT table looking for the first free      */
  /* entry.                                               */
  cluster = idx;
  for (;;)
  {
#ifdef CHECK_FAT_DURING_CLUSTER_ALLOC /* slower but nice side effect ;-) */
    if (next_cluster(fnp->f_dpb, idx) == FREE)
#else
    if (is_free_cluster(fnp->f_dpb, idx))
#endif
    {
      cluster = idx;
      break;
    }
    idx++;
    /* wrap the search just in case there are free clusters before */
    /* dpb_(x)cluster (the fsinfo entry is just a hint!) */
    if (idx > size) idx = 2;
    if (idx == cluster) {
      /* No empty clusters, disk is FULL!                     */
      cluster = UNKNCLUSTER;
      idx = LONG_LAST_CLUSTER;
      break;
    }
  }

#ifdef WITHFAT32
  if (is_fat32)
  {
    d.dpb_xcluster(cluster);
    /* return the free entry                                */
    write_fsinfo(fnp->f_dpb);
    return idx;
  }
#endif

  d.cluster((UWORD)cluster);
  /* return the free entry                                */
  return idx;
}

/* initialize directory entry (creation/access stamps 0 as per MS-DOS 7.10) */
STATIC void init_direntry(struct dirent *dentry, unsigned attrib, CLUSTER cluster, const char *name)
{
  nf_memset(dentry, 0, sizeof(struct dirent));
  dos_api_memcpy(dentry->dir_name, name, FNAME_SIZE + FEXT_SIZE);
#ifdef WITHFAT32
  dentry->dir_start_high = (UWORD)(cluster >> 16);
#endif
  dentry->dir_start = (UWORD)cluster;
  dentry->dir_attrib = (UBYTE)attrib;
  /* set create and last modified time & date */
  dentry->dir_crtime = dentry->dir_time = dos_gettime();
  dentry->dir_crdate = dentry->dir_date = dos_getdate();
}


COUNT dos_setfattr(BYTE *name, UWORD attrp)
{
  return dos_setfattr_ref(fdos_path_native((const char *)name), attrp);
}

/*                                                              */
/* create a directory - returns success or a negative error     */
/* number                                                       */
/*                                                              */
COUNT dos_mkdir_ref(fdos_path_ref dir)
{
  REG f_node_ptr fnp;
  CLUSTER free_fat, parent;
  COUNT ret;

  /* check that the resulting combined path does not exceed
     the 67 MAX_CDSPATH limit. this leads to problems:
     A) you can't CD to this directory later
     B) you can't create files in this subdirectory
     C) the created dir will not be found later, so you
     can create an unlimited amount of same dirs. this space
     is lost forever
   */
  if (fdos_path_len(dir, FDOS_PATHLEN) >= MAX_CDSPATH)  /* dir is already output of "truename" */
    return DE_PATHNOTFND;

  /* Check that we don't have a duplicate name, so if we  */
  /* find one, it's an error.                             */
  fnp = fnode_slot(0);
  ret = find_fname_ref(dir, D_ALL, fnp);
  if (ret != DE_FILENOTFND)
    return ret == SUCCESS ? DE_ACCESS : ret;

  parent = DM_GET32(fnp->f_dmp, dm_dircluster);

  ret = alloc_find_free_ref(fnp, dir);
  if (ret != SUCCESS)
    return ret;

  /* get an empty cluster, so that we make it into a      */
  /* directory.                                           */
  /* TE this has to be done (and failed) BEFORE the dir entry */
  /* is changed                                           */
  free_fat = find_fat_free(fnp);

  /* No empty clusters, disk is FULL! Translate into a    */
  /* useful error message.                                */
  if (free_fat == LONG_LAST_CLUSTER)
    return DE_HNDLDSKFULL;

  BYTE dm_name_pat[FNAME_SIZE + FEXT_SIZE];
  dmatch_read_name_pat(fnp->f_dmp, dm_name_pat);
  init_direntry(&fnp->f_dir, D_DIR, free_fat, dm_name_pat);

  /* Mark the cluster in the FAT as used and create new dir there */
  if (link_fat(fnp->f_dpb, free_fat, LONG_LAST_CLUSTER) != SUCCESS) /* free->last */
    return DE_HNDLDSKFULL; /* should never happen */

  /* clean out the new directory */
  ret = clear_dir(fnp, free_fat);
  if (ret != SUCCESS)
    return ret;

  /* Write the new directory entry                         */
  if (!dir_write(fnp))
    return DE_ACCESS;

  /* Craft the new directory. Note that if we're in a new  */
  /* directory just under the root, ".." pointer is 0.     */

  dir_init_fnode(fnp, free_fat);
  DM_SET16(fnp->f_dmp, dm_entry, 0);
  find_free(fnp);

  /* Create the "." entry                                 */
  init_direntry(&fnp->f_dir, D_DIR, free_fat, ".          ");

  /* And put it out                                       */
  if (!dir_write(fnp))
    return DE_ACCESS;

  /* create the ".." entry                                */
  if (!find_free(fnp) && ((ret = extend_dir(fnp)) != SUCCESS))
    return ret;
#ifdef WITHFAT32
  {
    const dpb_ref d(fnp->f_dpb);
    if (d.dpb_fatsize() == 0 && parent == d.dpb_xrootclst())
      parent = 0;
  }
#endif
  /* use . to allow the compiler to merge duplicate strings */
  init_direntry(&fnp->f_dir, D_DIR, parent, ".          ");
  fnp->f_dir.dir_name[1] = '.';

  /* and put it out                                       */
  if (!dir_write(fnp))
    return DE_ACCESS;

  return SUCCESS;
}

COUNT dos_mkdir(BYTE *dir)
{
  return dos_mkdir_ref(fdos_path_native((const char *)dir));
}

/*                                                              */
/* wipe out all FAT entries starting from st for create, delete, etc. */
/*                                                              */
STATIC VOID wipe_out_clusters(dos_far_ptr /* -> struct dpb */ x86_dpbp, CLUSTER st)
{
  const dpb_ref d(x86_dpbp);
  REG CLUSTER next;
#ifdef WITHFAT32
  const BOOL is_fat32 = (d.dpb_fatsize() == 0);
#endif

  /* Loop from start until either a FREE entry is         */
  /* encountered (due to a fractured file system) of the  */
  /* last cluster is encountered.                         */
  while (st != LONG_LAST_CLUSTER) /* remove clusters at start until empty */
  {
    /* get the next cluster pointed to              */
    next = next_cluster(x86_dpbp, st);

    /* just exit if a damaged file system exists    */
    if (next <= 1)
      return;

    /* zap the FAT pointed to                       */
    if (link_fat(x86_dpbp, st, FREE) != SUCCESS) /* nonfree->free */
      return; /* better abort on error */

    /* and the start of free space pointer          */
#ifdef WITHFAT32
    if (is_fat32)
    {
      const ULONG hint = d.dpb_xcluster();
      if (hint == UNKNCLUSTER || hint > st)
        d.dpb_xcluster(st);
    }
    else
#endif
    {
      const UWORD hint = d.cluster();
      if (hint == UNKNCLUSTER || hint > (UWORD)st)
        d.cluster((UWORD)st);
    }

    /* and just follow the linked list              */
    st = next;
  }
#ifdef WITHFAT32
  if (is_fat32)
    write_fsinfo(x86_dpbp);
#endif
}

/* wipe out all FAT entries for create, delete, etc.            */
/* called by delete_dir_entry and dos_open open in O_TRUNC mode */
STATIC VOID wipe_out(f_node_ptr fnp)
{
  /* if not already free and valid file, do it */
  CLUSTER cluster = getdstart(fnp->f_dpb, &fnp->f_dir);
  if (cluster != FREE)
    wipe_out_clusters(fnp->f_dpb, cluster);
  /* no flushing here: could get lost chain or "crosslink seed" but */
  /* it would be annoying if mass-deletes could not use BUFFERS...  */
}

COUNT delete_dir_entry(f_node_ptr fnp)
{
  COUNT rc;

  /* Ok, so we can delete. Start out by           */
  /* clobbering all FAT entries for this file     */
  /* (or, in English, truncate the FAT).          */
  if ((rc = remove_lfn_entries(fnp)) < 0)
    return rc;

  wipe_out(fnp);
  *(fnp->f_dir.dir_name) = DELETED;

  /* The directory has been modified, so set the  */
  /* bit before closing it, allowing it to be     */
  /* updated                                      */
  if (!dir_write(fnp))
    return DE_ACCESS;

  /* SUCCESSful completion, return it             */
  return SUCCESS;
}

/* dos_delete() was declared in proto.h and called
   from DosDelete() (see dosfns.c), but never implemented anywhere in this
   port - INT 21h AH=41h (DELETE FILE) had no working backend at all.
   Migrated as-is from upstream fatfs.c; depends only on find_fname() and
   delete_dir_entry(), both already present above in this file. */
COUNT dos_delete_ref(fdos_path_ref path, int attrib)
{
  REG f_node_ptr fnp = fnode_slot(0);

  /* Check that we don't have a duplicate name, so if we  */
  /* find one, it's an error.                             */
  int ret = find_fname_ref(path, attrib, fnp);
  if (ret == SUCCESS)
  {
    /* Do not delete directories or r/o files       */
    /* lfn entries and volume labels are only found */
    /* by find_fname() if attrib is set to a        */
    /* special value                                */
    if (fnp->f_dir.dir_attrib & (D_RDONLY | D_DIR))
      return DE_ACCESS;

    return delete_dir_entry(fnp);
  }
  else
    /* No such file, return the error               */
    return ret;
}

COUNT dos_delete(BYTE *path, int attrib)
{
  return dos_delete_ref(fdos_path_native((const char *)path), attrib);
}

COUNT dos_rmdir_ref(fdos_path_ref path)
{
  REG f_node_ptr fnp;

  /* prevent removal of the current directory of that drive */
  dos_far_ptr /* -> struct cds */ _cds = get_cds((COUNT)fdos_path_get(path, 0) - 'A');
  if (cds_current_path_equals_ref(_cds, path))
    return DE_RMVCUDIR;

  /* Check that we're not trying to remove the root!      */
  if (fdos_path_get(path, 2) == '\\' && fdos_path_get(path, 3) == '\0')
    return DE_ACCESS;

  /* Check that the directory is empty. Only the  */
  /* "." and ".." are permissable.                */
  fnp = dir_open_ref(path, FALSE, fnode_slot(0));
  if (fnp == NULL)
    return DE_PATHNOTFND;

  /* Directories may have attributes, but if other than 'archive'      */
  /* or 'read only' then deny i.e. do not allow (SYSTEM|HIDDEN)        */
  /* directory to be deleted.                                          */
  if (fnp->f_dir.dir_attrib & ~(D_DIR | D_RDONLY | D_ARCHIVE))
    return DE_ACCESS;

  dir_read(fnp);
  /* 1st entry should be ".", else directory corrupt or not empty */
  if (fnp->f_dir.dir_name[0] != '.' || fnp->f_dir.dir_name[1] != ' ')
    return DE_ACCESS;

  DM_SET16(fnp->f_dmp, dm_entry, (UWORD)(DM_GET16(fnp->f_dmp, dm_entry) + 1));
  dir_read(fnp);
  /* second entry should be ".." */
  if (fnp->f_dir.dir_name[0] != '.' || fnp->f_dir.dir_name[1] != '.')
    return DE_ACCESS;

  /* Now search through the directory and make certain */
  /* that there are no entries                         */
  DM_SET16(fnp->f_dmp, dm_entry, (UWORD)(DM_GET16(fnp->f_dmp, dm_entry) + 1));
  while (dir_read(fnp) == 1)
  {
    /* If anything was found, exit with an error.   */
    if (fnp->f_dir.dir_name[0] != DELETED && fnp->f_dir.dir_attrib != D_LFN)
      return DE_ACCESS;
    DM_SET16(fnp->f_dmp, dm_entry, (UWORD)(DM_GET16(fnp->f_dmp, dm_entry) + 1));
  }

  /* next, split the passed dir into components (i.e. -   */
  /* path to new directory and name of new directory      */
  if (find_fname_ref(path, D_ALL, fnp) != SUCCESS)
    /* this error should not happen because dir_open() succeeded above */
    return DE_PATHNOTFND;

  return delete_dir_entry(fnp);
}

COUNT dos_rmdir(BYTE *path)
{
  return dos_rmdir_ref(fdos_path_native((const char *)path));
}

/* declared in proto.h, needed by dos_findnext()
   (wildcard 8.3 name matching), but never implemented in this port.
   Migrated verbatim from upstream fatfs.c. */
BOOL fcmp_wild(const char * s1, const char * s2, unsigned n)
{
  for ( ; n--; ++s1, ++s2)
    if (*s1 != '?' && *s1 != *s2)
      return FALSE;
  return TRUE;
}

} /* extern "C" */
