#include <pico.h>
#include <pico/time.h>
#include <hardware/pio.h>
#include <ctype.h>
#include "286/cpu.h"
#include "bios/bios.h"
#include "fdos.h"
#include "i8254.h"

#include "hdr/kconfig.h"
#include "hdr/portab.h"

#include "hdr/ddate.h"
#include "hdr/dtime.h"
#include "hdr/error.h"
#include "hdr/clock.h"
#include "hdr/device.h"
#include "hdr/sft.h"
#include "hdr/kbd.h"
#include "hdr/fcb.h"
#include "hdr/fat.h"
#include "hdr/pcb.h"
#include "hdr/dirmatch.h"
#include "hdr/fnode.h"
#include "hdr/mcb.h"
#include "hdr/lol.h"
#include "hdr/dcb.h"
#include "hdr/cds.h"
#include "hdr/tail.h"
#include "hdr/process.h"
#include "hdr/version.h"
#include "proto.h"
#include "globals.h"
#include "hdr/debug.h"
#include "hdr/buffer.h"
#include "hdr/file.h"
#include "config.h"
#include "hdr/network.h"
#include "init-mod.h"
#include "dyndata.h"

#define printf(...) dos_printf(__VA_ARGS__)

/*
    fnode[] - internal scratch file nodes used while servicing a single
    DOS API call (open/read/write/seek/close/etc). See the comment on
    f_dpb/f_dmp in fnode.h for why these stay as plain native ARM
    structures/pointers, unlike sft/cds: no guest code or DOS API ever
    holds a reference to an f_node, only to the SFT index that
    sft_to_fnode()/fnode_to_sft() below translate to/from one.

    Migrated from globals.h (GLOBAL struct f_node fnode[2]). fnode[0]
    is used for ordinary single-file operations; fnode[1] is only
    needed by operations that touch two files at once (rename, and
    DOS's "move within filesystem"), neither of which is implemented
    yet - but the second slot is kept here so later code matches the
    original's indexing (&fnode[0] / &fnode[1]) instead of needing a
    separate single-entry special case.
*/
struct f_node fnode[2];

/* /// Added - Ron Cemer */
/* If more than one SFT has a file open, and a write
   occurs, this function must be called to propagate the
   results of that write to the other f_nodes which have
   that file open.  Note that this function only has an
   effect if SHARE is installed.  This is for compatibility
   reasons, since DOS without SHARE does not share changes
   between two or more open instances of the same file
   unless these instances were generated by dup() or dup2(). */
/*
    Migrated from fatfs.c. Differences from the original:
      - sfthead/sp->sftt_next walk LoL->sfthead (a dos_far_ptr) via
        ARM_PTR()/far_is_end(), the same way get_free_sft() above
        already does, instead of following a near "sfttbl FAR *"
        chain directly.
      - fnp->f_dpb (a native struct dpb*, see fnode.h) is compared
        against sftp->sft_dcb (a dos_far_ptr) by converting f_dpb to
        a dos_far_ptr first (x86_FAR_PTR(), recovering the segment
        from LoL->DPBp, exactly as sft_to_fnode()/fnode_to_sft() do)
        and comparing both fields of the resulting dos_far_ptr -
        comparing a native pointer to a dos_far_ptr directly would
        not even compile, let alone mean the same thing.
      - the collect==-1 (DosCloseSft) branch is migrated as-is, but
        nothing in this codebase calls merge_file_changes() with
        collect==-1 yet (dos_open()/dos_close() below only ever pass
        TRUE/FALSE) - DosCloseSft() itself is not implemented yet
        either (see proto.h), so that branch is unreachable for now,
        not silently wrong.
*/
STATIC int merge_file_changes(f_node_ptr fnp, int collect)
{
  int i, j;
  sft *sftp;
  dos_far_ptr x86_sp;
  dos_far_ptr fnp_dpb_far;

  if (!IsShareInstalled(FALSE))
    return SUCCESS;

  fnp_dpb_far = x86_FAR_PTR(FP_SEG(LoL->DPBp), fnp->f_dpb);

  i = 0;
  for (x86_sp = LoL->sfthead; !far_is_end(x86_sp); )
  {
    sfttbl *sp = (sfttbl *)ARM_PTR(x86_sp);

    for (j = sp->sftt_count, sftp = sp->sftt_table; --j >= 0; sftp++, i++)
    {
      if (i != fnp->f_sft_idx && sftp->sft_count != 0
          && FP_SEG(fnp_dpb_far) == FP_SEG(sftp->sft_dcb)
          && FP_OFF(fnp_dpb_far) == FP_OFF(sftp->sft_dcb)
          && (fnp->f_dir.dir_attrib & D_VOLID) == 0
          && (sftp->sft_attrib & D_VOLID) == 0
          && fnp->f_diridx == sftp->sft_diridx
          && fnp->f_dirsector == sftp->sft_dirsector
        ) /* same file, but different FD */
      {
        if (collect == -1)
        {
          /* set attrib: close open files */
          int rc = DosCloseSft(i, FALSE);
          if (rc != SUCCESS)
            return rc;
        }
        else if (collect)
        {
          /* We're collecting file changes from any other
             SFT which refers to this file. */
          if ((sftp->sft_mode & O_ACCMODE) != RDONLY)
          {
            setdstart(fnp->f_dpb, &fnp->f_dir, sftp->sft_stclust);
            fnp->f_dir.dir_size = sftp->sft_size;
            fnp->f_dir.dir_date = sftp->sft_date;
            fnp->f_dir.dir_time = sftp->sft_time;
            return SUCCESS;
          }
        }
        else
        {
          /* We just made changes to this file, so we are
             distributing these changes to the other f_nodes
             which refer to this file. */
          sftp->sft_stclust = getdstart(fnp->f_dpb, &fnp->f_dir);
          sftp->sft_size = fnp->f_dir.dir_size;
          sftp->sft_date = fnp->f_dir.dir_date;
          sftp->sft_time = fnp->f_dir.dir_time;
        }
      }
    }

    x86_sp = sp->sftt_next;
  }
  return SUCCESS;
}


/*
    sft_to_fnode(fd)/fnode_to_sft(fnp) - copy an open file's state
    between its SFT entry (guest-visible, dos_far_ptr-based) and
    fnode[0] (native scratch struct used while servicing the call).

    Migrated from fatfs.c. sft_dcb/f_dpb need an explicit ARM_PTR()/
    x86_FAR_PTR() conversion on the way in/out (see fnode.h) - in the
    original this is a plain pointer assignment, since sft_dcb and
    f_dpb are both "struct dpb FAR *" there. We recover the dpb's
    guest segment from LoL->DPBp, since all dpb entries are allocated
    as one contiguous array sharing a single segment (see update_dcb()/
    FsConfig() above).
*/
STATIC f_node_ptr sft_to_fnode(int fd)
{
  sft FAR *sftp = idx_to_sft(fd);
  f_node_ptr fnp = &fnode[0];

  fnp->f_sft_idx = (UBYTE)fd;

  fnp->f_flags = sftp->sft_flags;

  fnp->f_dir.dir_attrib = sftp->sft_attrib;
  memcpy(fnp->f_dir.dir_name, sftp->sft_name, FNAME_SIZE + FEXT_SIZE);
  fnp->f_dir.dir_time = sftp->sft_time;
  fnp->f_dir.dir_date = sftp->sft_date;
  fnp->f_dir.dir_size = sftp->sft_size;
  fnp->f_dpb = (struct dpb *)ARM_PTR(sftp->sft_dcb);
  setdstart(fnp->f_dpb, &fnp->f_dir, sftp->sft_stclust);

  fnp->f_diridx = sftp->sft_diridx;
  fnp->f_dirsector = sftp->sft_dirsector;
  fnp->f_offset = sftp->sft_posit;
  fnp->f_cluster = sftp->sft_cuclust;
#ifdef WITHFAT32
  fnp->f_cluster_offset = sftp->sft_relclust |
    ((ULONG)sftp->sft_relclust_high << 16);
#else
  fnp->f_cluster_offset = sftp->sft_relclust;
#endif
  return fnp;
}

/*
    dos_close(fd) - the FAT-level half of closing a file: stamp the
    modification time/date if the file was written and the SFT's
    "date already set" bit isn't set, propagate any in-memory changes
    to other SFTs pointing at the same file, then write the directory
    entry back (dir_write_update(), which - see its comment above -
    only actually writes anything if the file was modified).

    Migrated from fatfs.c verbatim.
*/
COUNT dos_close(COUNT fd)
{
  /* Translate the fd into a useful pointer                       */
  f_node_ptr fnp = sft_to_fnode(fd);

  if (!(fnp->f_flags & SFT_FCLEAN))
  {
    if (!(fnp->f_flags & SFT_FDATE))
    {
      fnp->f_dir.dir_time = dos_gettime();
      fnp->f_dir.dir_date = dos_getdate();
    }

    merge_file_changes(fnp, FALSE);     /* /// Added - Ron Cemer */
  }
  fnp->f_sft_idx = 0xff;

  return dir_write_update(fnp, TRUE) ? SUCCESS : DE_INVLDHNDL;
}

/*
    dos_extend(fnp, emptywrite) - grow a file by allocating one more
    cluster past its current end (write path).

    /// TODO: stub for this iteration. Needs find_fat_free() (not
    /// migrated, same as extend()'s comment above) to allocate a
    /// cluster. Always reports the disk as full - rwblock() (below)
    /// only calls this for XFR_WRITE, which nothing in this codebase
    /// invokes yet (DosWrite()/AH=40h are not migrated), so this is
    /// unreachable for now, not silently wrong.

    Migrated from fatfs.c (signature only; body replaced as above).
*/
STATIC COUNT dos_extend(f_node_ptr fnp, BOOL emptywrite)
{
  UNREFERENCED_PARAMETER(fnp);
  UNREFERENCED_PARAMETER(emptywrite);
  return DE_HNDLDSKFULL;
}


STATIC void fnode_to_sft(f_node_ptr fnp)
{
  sft FAR *sftp = idx_to_sft(fnp->f_sft_idx);

  sftp->sft_flags = fnp->f_flags;

  sftp->sft_attrib = fnp->f_dir.dir_attrib;
  memcpy(sftp->sft_name, fnp->f_dir.dir_name, FNAME_SIZE + FEXT_SIZE);
  sftp->sft_time = fnp->f_dir.dir_time;
  sftp->sft_date = fnp->f_dir.dir_date;
  sftp->sft_size = fnp->f_dir.dir_size;
  sftp->sft_stclust = getdstart(fnp->f_dpb, &fnp->f_dir);

  sftp->sft_diridx = fnp->f_diridx;
  sftp->sft_dirsector = fnp->f_dirsector;
  sftp->sft_dcb = x86_FAR_PTR(FP_SEG(LoL->DPBp), fnp->f_dpb);
  sftp->sft_posit = fnp->f_offset;
  sftp->sft_cuclust = fnp->f_cluster;
  sftp->sft_relclust = (UWORD)fnp->f_cluster_offset;
#ifdef WITHFAT32
  sftp->sft_relclust_high = (UWORD)(fnp->f_cluster_offset >> 16);
#endif
}

/*
    shrink_file(fnp) - release every cluster past fnp's current file
    position, for a write that truncates a file mid-stream.

    /// TODO: stub for this iteration. Needs to walk and free the FAT
    /// chain past the new end of file - not migrated, same reasoning
    /// as dos_extend() above (only reachable from a XFR_WRITE caller,
    /// none of which exist yet in this codebase).

    Migrated from fatfs.c (signature only; body replaced as above).
*/
STATIC int shrink_file(f_node_ptr fnp)
{
  UNREFERENCED_PARAMETER(fnp);
  printf("PANIC: shrink_file() called but not implemented\n");
  for (;;) ;
}

/*
    rwblock(fd, buffer, count, mode) - the core of DosRead()/DosWrite()
    for a regular (non-device) file: transfer "count" bytes between
    "buffer" and the file at fd's current position, advancing it.

    Migrated from fatfs.c. Differences from the original:
      - buffer is a dos_far_ptr on entry (it comes straight from the
        guest program via DS:DX, like truename()'s src - see "support
        both pointer kinds" in fnode.h's notes), converted to a native
        pointer once up front via ARM_PTR(), the same reasoning as
        truename()'s migration note: there is no adjust_far()-equivalent
        normalization step needed here either, since ARM_PTR()/
        EFFECTIVE() compute a plain linear address with no 16-bit
        wraparound to guard against. The original's repeated
        "buffer = adjust_far(buffer + xfr_cnt)" becomes plain native
        pointer arithmetic ("buffer += xfr_cnt").
      - fmemcpy() calls become plain memcpy(): bp->b_buffer is native,
        and buffer is now native too (per the point above), so there
        is no far pointer left to translate.
      - dskxfer() already takes a native BYTE* (see its definition
        above), so the "complete sectors" fast path passes buffer to
        it directly, same as the original passed its (far) buffer.
*/
long rwblock(COUNT fd, dos_far_ptr x86_buffer, UCOUNT count, int mode)
{
  /* Translate the fd into an fnode pointer, since all internal   */
  /* operations are achieved through fnodes.                      */
  REG f_node_ptr fnp = sft_to_fnode(fd);
  REG struct buffer *bp;
  UCOUNT xfr_cnt = 0;
  UCOUNT ret_cnt = 0;
  unsigned secsize;
  unsigned to_xfer = count;
  ULONG currentblock;
  BYTE *buffer = (BYTE *)ARM_PTR(x86_buffer);

  if (mode==XFR_WRITE)
  {
    fnp->f_dir.dir_attrib |= D_ARCHIVE;
    /* mark file as modified and set date not valid any more */
    fnp->f_flags &= ~(SFT_FCLEAN|SFT_FDATE); 
    
    if (dos_extend(fnp, count == 0) != SUCCESS)
    {
      /* ecm: control flow may end up here if CX = 0000h and
                the extending failed to allocate a cluster
                behind the last needed. in this case, our
                return here of 0 happens to be correct and
                indicates the extension succeeded. */
      fnode_to_sft(fnp);
      return 0;
    }
    /* ecm: if CX = 0000h and seek was on a cluster boundary > size,
                the dos_extend call will have allocated one cluster
                too many. this is truncated later without problems.
                but does this aid fragmentation maybe ?
            if CX > 0000h then we want to write to the cluster
                anyway, so extending to the cluster that starts at
                the boundary is desired. */
  }
  
  /* Test that we are really about to do a data transfer. If the  */
  /* count is zero and the mode is XFR_READ, just exit. (Any      */
  /* read with a count of zero is a nop).                         */
  /*                                                              */
  /* A write (mode is XFR_WRITE) is a special case.  It sets the  */
  /* file length to the current length (truncates it).            */
  /*                                                              */
  /* NOTE: doing this up front saves a lot of headaches later.    */

  if (count == 0)
  {
    /* NOTE: doing this up front made a lot of headaches later :-( TE */
    /* FAT allocation has to be extended if necessary              TE */
    /* Now done in dos_extend                                      BO */
    /* remove all the following allocated clusters in shrink_file     */
    if (mode == XFR_WRITE)
    {
      fnp->f_dir.dir_size = fnp->f_offset;
      if (shrink_file(fnp) < 0) /* this is the only call to shrink_file... */
        return DE_ACCESS;
      /* why does empty write -always- truncate to current offset? */
    }
    fnode_to_sft(fnp);
    return 0;
  }

  /* prevent overwriting beginning of file when write exceeds 4GB,
     i.e. when overflow of offset occurs, return error on write   */
  if (fnp->f_offset + count < fnp->f_offset)   /* unsigned overflow */
  {                                                                 
    if (mode == XFR_WRITE)         
    {
      /*  can't extend beyond 4G so return '0 byte written, DISK_FULL */
      return DE_HNDLDSKFULL;
    }
    /* else XFR_READ should end automatically at EOF */
  }               

  /* The variable secsize will be used later.                     */
  secsize = fnp->f_dpb->dpb_secsize;

  /* Do the data transfer. Use block transfer methods so that we  */
  /* can utilize memory management in future DOS-C versions.      */
  while (ret_cnt < count)
  {
    unsigned sector, boff;

    /* Do an EOF test and return whatever was transferred   */
    if (mode == XFR_READ && fnp->f_offset >= fnp->f_dir.dir_size)
    {
      fnode_to_sft(fnp);
      return ret_cnt;
    }

    /* Position the file to the fnode's pointer position. This is   */
    /* done by updating the fnode's cluster, block (sector) and     */
    /* byte offset so that read or write becomes a simple data move */
    /* into or out of the block data buffer.                        */

    /* The more difficult scenario is the (more common)     */
    /* file offset case. Here, we need to take the fnode's  */
    /* offset pointer (f_offset) and translate it into a    */
    /* relative cluster position, cluster block (sector)    */
    /* offset (sector) and byte offset (boff). Once we      */
    /* have this information, we need to translate the      */
    /* relative cluster position into an absolute cluster   */
    /* position (f_cluster). This is unfortunate because it */
    /* requires a linear search through the file's FAT      */
    /* entries.                                              */
    if (map_cluster(fnp, mode) != SUCCESS)
    {
      fnode_to_sft(fnp);
      return ret_cnt;
    }
    if (mode == XFR_WRITE)
    {
      merge_file_changes(fnp, FALSE);   /* /// Added - Ron Cemer */
    }

    /* Compute the block within the cluster and the offset  */
    /* within the block.                                    */
    sector = (UBYTE)(fnp->f_offset / secsize) & fnp->f_dpb->dpb_clsmask;
    boff = (UWORD)(fnp->f_offset % secsize);

    currentblock = clus2phys(fnp->f_cluster, fnp->f_dpb) + sector;

    /* see comments above */

    if (boff == 0)              /* complete sectors only */
    {
      static ULONG startoffset;
      UCOUNT sectors_to_xfer, sectors_wanted;

      startoffset = fnp->f_offset;
      sectors_wanted = to_xfer;

      /* avoid EOF problems */
      if (mode == XFR_READ && to_xfer > fnp->f_dir.dir_size - fnp->f_offset)
        sectors_wanted = (UCOUNT)(fnp->f_dir.dir_size - fnp->f_offset);
      
      sectors_wanted /= secsize;

      if (sectors_wanted == 0)
        goto normal_xfer;

      sectors_to_xfer = fnp->f_dpb->dpb_clsmask + 1 - sector;

      sectors_to_xfer = min(sectors_to_xfer, sectors_wanted);

      fnp->f_offset += sectors_to_xfer * secsize;

      while (sectors_to_xfer < sectors_wanted)
      {
        if (map_cluster(fnp, mode) != SUCCESS)
          break;

        if (clus2phys(fnp->f_cluster, fnp->f_dpb) !=
            currentblock + sectors_to_xfer)
          break;

        sectors_to_xfer += fnp->f_dpb->dpb_clsmask + 1;

        sectors_to_xfer = min(sectors_to_xfer, sectors_wanted);

        fnp->f_offset = startoffset + sectors_to_xfer * secsize;

      }

      xfr_cnt = sectors_to_xfer * secsize;

      /* avoid caching trouble */

      DeleteBlockInBufferCache(currentblock,
                               currentblock + sectors_to_xfer - 1,
                               fnp->f_dpb->dpb_unit, mode);

      if (dskxfer(fnp->f_dpb->dpb_unit,
                  currentblock,
                  buffer, sectors_to_xfer,
                  mode == XFR_READ ? DSKREAD : DSKWRITE))
      {
        fnp->f_offset = startoffset;
        fnode_to_sft(fnp);
        return DE_ACCESS;
      }

      goto update_pointers;
    }

    /* normal read: just the old, buffer = sector based read */
  normal_xfer:

    /* Get the block we need from cache                     */
    bp = getblock(currentblock, fnp->f_dpb->dpb_unit);

    if (bp == NULL)             /* (struct buffer *)0 --> DS:0 !! */
    {
      fnode_to_sft(fnp);
      return ret_cnt;
    }

    /* transfer a block                                     */
    /* Transfer size as either a full block size, or the    */
    /* requested transfer size, whichever is smaller.       */
    /* Then compare to what is left, since we can transfer  */
    /* a maximum of what is left.                           */
    xfr_cnt = min(to_xfer, secsize - boff);
    if (mode == XFR_READ)
      xfr_cnt = (UWORD) min(xfr_cnt, fnp->f_dir.dir_size - fnp->f_offset);

    if (mode == XFR_WRITE)
    {
      memcpy(&bp->b_buffer[boff], buffer, xfr_cnt);
      bp->b_flag |= BFR_DIRTY | BFR_VALID;
    }
    else
    {
      memcpy(buffer, &bp->b_buffer[boff], xfr_cnt);
    }

    /* complete buffer transferred ? 
       probably not reused later
     */
    if (xfr_cnt == sizeof(bp->b_buffer) ||
        (mode == XFR_READ && fnp->f_offset + xfr_cnt == fnp->f_dir.dir_size))
    {
      bp->b_flag |= BFR_UNCACHE;
    }

    /* update pointers and counters                         */
    fnp->f_offset += xfr_cnt;

  update_pointers:
    ret_cnt += xfr_cnt;
    to_xfer -= xfr_cnt;
    buffer += xfr_cnt;
    if (mode == XFR_WRITE)
    {
      if (fnp->f_offset > fnp->f_dir.dir_size)
      {
        fnp->f_dir.dir_size = fnp->f_offset;
      }
      merge_file_changes(fnp, FALSE);     /* /// Added - Ron Cemer */
    }
  }
  fnode_to_sft(fnp);
  return ret_cnt;
}

void dos_merge_file_changes(int fd)
{
  merge_file_changes(sft_to_fnode(fd), FALSE);
}

/*
    find_fname(path, attr, fnp) - find the directory entry for "path"
    (full path including filename), with the given attribute mask
    applied the same way DOS's FindFirst does.

    Migrated from fatfs.c verbatim.
*/
STATIC int find_fname(const char *path, int attr, f_node_ptr fnp)
{
  /* check for leading backslash and open the directory given that */
  /* contains the file given by path.                              */
  if ((fnp = split_path(path, fnp)) == NULL)
    return DE_PATHNOTFND;

  while (dir_read(fnp) == 1)
  {
    if (fcbmatch(fnp->f_dir.dir_name, fnp->f_dmp->dm_name_pat)
        && (fnp->f_dir.dir_attrib & ~(D_RDONLY | D_ARCHIVE | attr)) == 0)
    {
      return SUCCESS;
    }
    fnp->f_dmp->dm_entry++;
  }
  return DE_FILENOTFND;
}

/* Open a file given the path. Flags is 0 for read, 1 for write and 2   */
/* for update.                                                          */
/* Returns an long where the high word is a status code and the low     */
/* word is an integer file descriptor or a negative error code          */
/* see DosOpenSft(), dosfns.c for an explanation of the flags bits      */
/* directory opens are allowed here; these are not allowed by DosOpenSft*/

/*
    Migrated from fatfs.c verbatim, except for the O_TRUNC and
    DE_FILENOTFND-with-O_CREAT branches:
      - O_TRUNC needs wipe_out() (release the existing file's FAT
        chain and truncate to zero) - not migrated yet.
      - O_CREAT (the file doesn't exist) needs alloc_find_free()
        (allocate a free directory slot/cluster for a brand-new file)
        and init_direntry()/dir_write() to write it out - none of
        which are migrated yet either.
    Both report a clear, deliberate "not implemented" error
    (DE_ACCESS - there is no specific "not implemented" DOS error
    code) instead of silently doing nothing or corrupting state, so
    they fail loudly rather than pretending to succeed. The O_OPEN
    (open existing file) path - this iteration's actual goal - is
    migrated in full, including the shared tail (merge_file_changes()/
    fnode_to_sft()) that runs after any of the three branches.
*/
int dos_open(char *path, unsigned flags, unsigned attrib, int fd)
{
  REG f_node_ptr fnp = sft_to_fnode(fd);
  int status = find_fname(path, D_ALL | attrib, fnp);

  /* Check that we don't have a duplicate name, so if we  */
  /* find one, truncate it (O_CREAT).                     */
  if (status == SUCCESS)
  {
    unsigned char dir_attrib = fnp->f_dir.dir_attrib;
    if (flags & O_TRUNC)
    {
      /* The only permissable attribute is archive,   */
      /* check for any other bit set. If it is, give  */
      /* an access error.                             */
      if ((dir_attrib & (D_RDONLY | D_DIR | D_VOLID))
          || (dir_attrib & ~D_ARCHIVE & ~attrib))
        return DE_ACCESS;

      /// TODO: wipe_out(fnp) (release the existing file's FAT chain
      /// and truncate it to zero) is not implemented yet.
      printf("dos_open: O_TRUNC not implemented yet\n");
      return DE_ACCESS;
    }
    else if (flags & O_OPEN)
    {
      /* force r/o open for FCB if the file is read-only */
      if ((flags & O_FCB) && (dir_attrib & D_RDONLY))
        flags = (flags & ~3) | O_RDONLY;

      /* Check permissions. -- JPP
         (do not allow to open volume labels/directories,
          and do not allow writing to r/o files) */
      if ((dir_attrib & (D_DIR | D_VOLID)) ||
          ((dir_attrib & D_RDONLY) && ((flags & O_ACCMODE) != O_RDONLY)))
        return DE_ACCESS;
      status = S_OPENED;
    }
    else
    {
      return DE_FILEEXISTS;
    }
  }
  else if (status == DE_FILENOTFND && (flags & O_CREAT))
  {
    /// TODO: alloc_find_free(fnp, path) (allocate a free directory
    /// slot/cluster for a brand-new file) is not implemented yet.
    printf("dos_open: O_CREAT (new file) not implemented yet\n");
    return DE_ACCESS;
  }
  else
  {
    /* open: If we can't find the file, just return a not    */
    /* found error.                                          */
    return status;
  }

  /* Now change to file                                   */
  fnp->f_sft_idx = fd;
  fnp->f_offset = 0l;
  fnp->f_cluster_offset = 0;

  fnp->f_flags &= ~SFT_FDATE;
  /* use FCLEAN even on replaced/created files: the bit is reset */
  /* if the file is written to later                             */
  fnp->f_flags |= SFT_FCLEAN;
  if (status != S_OPENED)
  {
    /// TODO: init_direntry()/dir_write() are not implemented yet -
    /// unreachable for now, since both branches that set status to
    /// anything other than S_OPENED return early above instead.
    printf("PANIC: dos_open reached the O_CREAT/O_TRUNC tail unexpectedly\n");
    for (;;) ;
  }

  merge_file_changes(fnp, status == S_OPENED); /* /// Added - Ron Cemer */
  /* /// Moved from above.  - Ron Cemer */
  fnp->f_cluster = getdstart(fnp->f_dpb, &fnp->f_dir);

  fnode_to_sft(fnp);
  return status;
}

/* DosCloseSft() (the real implementation - network redirector close,
   device-driver C_CLOSE request, SHARE deregistration, dos_close())
   is defined further down in this file, after dos_open() - it needs
   sft_to_fnode()/fnode_to_sft()/dos_close(), which aren't defined yet
   at this point. The prototype in proto.h is enough for the
   collect==-1 branch in merge_file_changes() above to compile. */

/*
    DosCloseSft(sft_idx, commitonly) - the real implementation behind
    INT 21h AH=3Eh (close) and the "commit" (AH=68h) call.

    Migrated from dosfns.c. Differences from the original:
      - sftp->sft_dev is a dos_far_ptr here (see sft.h), so
        BinaryCharIO() (which takes a pointer to a dos_far_ptr) is
        called against a local copy of it, the same way
        DeviceOpenSft() above already does; dh_attr is read through
        ARM_PTR(sftp->sft_dev) instead of "sftp->sft_dev->dh_attr"
        directly.
      - the SFT_FSHARED (network redirector) branch is migrated as-is
        but unreachable: SFT_FSHARED can only be set by the IS_NETWORK
        path in DosOpenSft(), which - see its comment - can never be
        taken in this codebase (no redirector exists to create a
        network drive). network_redirector_fp() always reports
        failure (see its definition above) regardless.
      - the SHARE-installed branch (share_close_file()) is left as a
        deliberate panic, same reasoning as DosOpenSft()'s SHARE
        branch above: IsShareInstalled() always returns FALSE, so it
        is unreachable right now, not silently wrong.
*/
COUNT DosCloseSft(int sft_idx, BOOL commitonly)
{
  sft *sftp = idx_to_sft(sft_idx);
  int result;

  if (sftp == (sft *) - 1)
    return DE_INVLDHNDL;

  internal_data->lpCurSft = x86_FAR_PTR(FP_SEG(LoL->sfthead), sftp);
/*
   remote sub sft_count.
 */
  if (sftp->sft_flags & SFT_FSHARED)
  {
    /// unreachable: see the function-level comment above.
    return network_redirector_fp(commitonly ? REM_FLUSH : REM_CLOSE, sftp);
  }

  if (sftp->sft_flags & SFT_FDEVICE)
  {
    struct dhdr *dev = (struct dhdr *)ARM_PTR(sftp->sft_dev);
    if (dev->dh_attr & SFT_FOCRM)
    {
      /* if Open/Close/RM bit in driver's attribute is set
       * then issue a Close request to the driver
       */
      dos_far_ptr devp = sftp->sft_dev;
      if (BinaryCharIO(&devp, 0, NULL, C_CLOSE) != SUCCESS)
        return DE_INVLDHNDL;
    }
    /* now just drop the count if a device */
    if (!commitonly)
      sftp->sft_count -= 1;
    return SUCCESS;
  }

  /* else call file system handler                     */
  result = dos_close(sft_idx);
  if (commitonly || result != SUCCESS)
    return result;

/* /// Added for SHARE *** CURLY BRACES ADDED ALSO!!! ***.  - Ron Cemer */
  if (sftp->sft_count == 1 && IsShareInstalled(TRUE))
  {
    /// unreachable: IsShareInstalled() always returns FALSE in this
    /// codebase. share_close_file() is not implemented, so this is
    /// left as a deliberate panic rather than silently doing nothing,
    /// in case that assumption ever stops holding.
    printf("PANIC: DosCloseSft reached share_close_file unexpectedly\n");
    for (;;) ;
  }
/* /// End of additions for SHARE.  - Ron Cemer */
  sftp->sft_count -= 1;
  return SUCCESS;
}

/*
    DosClose(hndl) - INT 21h AH=3Eh: close a DOS file handle for the
    current process.

    Migrated from dosfns.c. p is a native pointer here (see
    get_free_hndl() above for the same "psp through
    internal_data->cu_psp" pattern).
*/
COUNT DosClose(COUNT hndl)
{
  psp *p = (psp *)ARM_PTR(MK_FP(internal_data->cu_psp, 0));
  int sft_idx = get_sft_idx(hndl);
  if (idx_to_sft(sft_idx) == (sft *) - 1)
    return DE_INVLDHNDL;
  /* We must close the (valid) file handle before any critical error */
  /* may occur, else e.g. ABORT will try to close the file twice,    */
  /* the second time after stdout is already closed */
  p->ps_filetab[hndl] = 0xff;
  /* Get the SFT block that contains the SFT      */
  return DosCloseSft(sft_idx, FALSE);
}

/*                                                                      */
/* split a path into it's component directory and file name             */
/*                                                                      */
/*
    Migrated from fatfs.c verbatim. The #ifdef DEBUG block needs an
    ARM_PTR() that the original doesn't: get_cds() here returns a
    dos_far_ptr (see fdos_21h.c), not a directly-dereferenceable
    pointer like the original's "struct cds FAR *".
*/
f_node_ptr split_path(const char * path, f_node_ptr fnp)
{
  /* check if the path ends in a backslash                        */
  if (path[strlen(path) - 1] == '\\')
    return (f_node_ptr) 0;

/*  11/29/99 jt
   * Networking and Cdroms. You can put in here a return.
   * Maybe a return of 0xDEADBEEF or something for Split or Dir_open.
   * Just to let upper level Fdos know its a sft, CDS function.
   * Right now for Networking there is no support for Rename, MkDir
   * RmDir & Delete.

   <insert code here or in dir_open. I would but it in Dir_open.
   Do the redirection in Network.c>

 */
#ifdef DEBUG
  if (((struct cds *)ARM_PTR(get_cds(path[0]-'A')))->cdsFlags & CDSNETWDRV)
  {
    printf("split path called for redirected file: `%s'\n", path);
    return (f_node_ptr) 0;
  }
#endif

  /* Translate the path into a useful pointer                     */
  return dir_open(path, TRUE, fnp);
}

/*
    dir_exists(path) - true if "path" names an existing directory.

    Migrated from fatfs.c verbatim.
*/
BOOL dir_exists(char * path)
{
  return split_path(path, &fnode[0]) != NULL;
}

/*
    dos_cd(PathName) - change the current directory (the part of
    CHDIR that updates the CDS once the new directory has been
    confirmed to exist).

    Migrated from fatfs.c. cdsp is a dos_far_ptr here (get_cds()
    returns one in this codebase, see fdos_21h.c), so the original's
    direct "cdsp->cdsStrtClst = ..." needs an ARM_PTR() first.
*/
int dos_cd(char *PathName)
{
  f_node_ptr fnp;
  struct cds *cdsp;

  /* now test for its existance. If it doesn't, return an error.  */
  if ((fnp = dir_open(PathName, FALSE, &fnode[0])) == NULL)
    return DE_PATHNOTFND;

  /* problem: RBIL table 01643 does not give a FAT32 field for the
     CDS start cluster. But we are not using this field ourselves */
  cdsp = (struct cds *)ARM_PTR(get_cds(PathName[0] - 'A'));
  cdsp->cdsStrtClst = (UWORD)fnp->f_dmp->dm_dircluster;
  return SUCCESS;
}
