[pc]
mem=8M
cpu=4
bios=native
vga_bios=vgabios.bin
redirector=1

; Disk images
raw_sd_hdd=1

[cpu]
gen=4
fpu=0

[frank-386]
pcspeaker=1
adlib=1
soundblaster=1
tandy=0
covox=1
mpu401=1
dss=0
mouse=0
nes_mouse=1
nes_joystick=0
usb_joystick=0
usb=DEVICE
cpu_freq=504
psram_freq=66
flash_freq=66
volume=15
voltage=-1
mouse_invert_y=0
