//
// Copyright (C) 1993-1996 Id Software, Inc.
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//

// D_main.c

#if 0 // VERSIONS RESTORATION: Move these down for convenience
#define	BGCOLOR		7
#define	FGCOLOR		8
#endif

#if defined(__WATCOMC__) || defined(ELF_MODE)
#include <dos.h>
#endif
#ifdef __WATCOMC__
#include <graph.h>
#include <sys\types.h>
#include <unistd.h>
#endif
#include <stdio.h>
#include <stdlib.h>
#include "DoomDef.h"
#include "soundst.h"
#include "DUtils.h"
#include <io.h>
#include <direct.h>


#if (APPVER_DOOMREV < AV_DR_DM1666P)
#define	BGCOLOR		1
#define	FGCOLOR		14
#elif (APPVER_DOOMREV < AV_DR_DM19)
#define	BGCOLOR		4
#define	FGCOLOR		15
#elif (APPVER_DOOMREV < AV_DR_DM19UP)
#define	BGCOLOR		7
#define	FGCOLOR		4
#elif (APPVER_DOOMREV < AV_DR_DM19U)
#define	BGCOLOR		3
#define	FGCOLOR		0
#else
#define	BGCOLOR		7
#define	FGCOLOR		8
#endif

#if (APPVER_DOOMREV < AV_DR_DM12)
extern int _wp1, _wp2, _wp3;
#else
extern int _wp1, _wp2, _wp3, _wp4;
#endif

#define MAXWADFILES 20
#if (APPVER_DOOMREV >= AV_DR_DM1666P)
char *wadfiles[MAXWADFILES];
#endif

boolean shareware;		// true if only episode 1 present
#if (APPVER_DOOMREV >= AV_DR_DM1666P)
boolean registered;
boolean commercial;
#endif
#if (APPVER_DOOMREV >= AV_DR_DM18FR)
boolean french;
#if (APPVER_DOOMREV >= AV_DR_DM19F)
boolean plutonia;
boolean tnt;
#endif
#endif

int devparm;                // M_CheckParm() result; nonzero means enabled
#if (APPVER_DOOMREV >= AV_DR_DM12)
int nomonsters;				// M_CheckParm() result; nonzero means enabled
int respawnparm;				// M_CheckParm() result; nonzero means enabled
#endif
#if (APPVER_DOOMREV >= AV_DR_DM1666P)
int fastparm;					// M_CheckParm() result; nonzero means enabled
#endif

boolean drone;

boolean modifiedgame;

boolean singletics = false; // debug flag to cancel adaptiveness



extern int soundVolume;
extern  int	sfxVolume;
extern  int	musicVolume;

extern  boolean	inhelpscreens;

skill_t startskill;
int startepisode;
int startmap;
#if (APPVER_DOOMREV >= AV_DR_DM12)
boolean autostart;
#endif

FILE *debugfile;

boolean advancedemo;




#if (APPVER_DOOMREV >= AV_DR_DM1666P)
char wadfile[1024];		// primary wad file
char mapdir[1024];      // directory of development maps
char basedefault[1024]; // default file
#endif


#if (APPVER_DOOMREV >= AV_DR_DM12)
void D_CheckNetGame(void);
#endif
void D_ProcessEvents(void);
void G_BuildTiccmd(ticcmd_t *cmd);
void D_DoAdvanceDemo(void);
void D_PageDrawer (void);
void D_AdvanceDemo (void);
void F_Drawer(void);
boolean F_Responder(event_t *ev);

#if (APPVER_DOOMREV < AV_DR_DM12)

#define	PL_DRONE	0x80				// bit flag in doomdata->player

int nodeingame[MAXNETNODES];
int nettics[MAXNETNODES];
ticcmd_t localcmds[BACKUPTICS];
ticcmd_t netcmds[MAXPLAYERS][BACKUPTICS];

doomdata_t netbuffer;

#define netnode netnode_eaj

int netnode;

#define int_632C8 int_632C8_eai

int int_632C8;

int gametime;
int maketic;

int numnetnodes;


void SendPacket(void);
void GetPackets(void);
int GetPacket(void);
void InitNetwork(void);
#endif

/*
===============================================================================

							EVENT HANDLING

Events are asyncronous inputs generally generated by the game user.

Events can be discarded if no responder claims them

===============================================================================
*/

event_t events[MAXEVENTS];
int eventhead;
int eventtail;

/*
================
=
= D_PostEvent
=
= Called by the I/O functions when input is detected
=
================
*/

void D_PostEvent (event_t *ev)
{
	events[eventhead] = *ev;
	eventhead = (++eventhead)&(MAXEVENTS-1);
}

/*
================
=
= D_ProcessEvents
=
= Send all the events of the given timestamp down the responder chain
=
================
*/

void D_ProcessEvents (void)
{
	event_t		*ev;

#if (APPVER_DOOMREV >= AV_DR_DM1666E)
	// IF STORE DEMO, DO NOT ACCEPT INPUT
	if ( commercial && (W_CheckNumForName("map01")<0) )
		return;
#endif

	for ( ; eventtail != eventhead ; eventtail = (++eventtail)&(MAXEVENTS-1) )
	{
		ev = &events[eventtail];
		if (M_Responder(ev))
			continue;               // menu ate the event
		G_Responder(ev);
	}
}

#if (APPVER_DOOMREV < AV_DR_DM12)


/*
===============
=
= TryRunTics
=
===============
*/

void TryRunTics (void)
{
	int i;
	int lowtic;
	int entertic;

	entertic = I_GetTime ();

	do
	{
		NetUpdate ();
		GetPackets ();

		lowtic = MAXINT;
		for (i=0 ; i<numnetnodes ; i++)
			if (nodeingame[i] && nettics[i] < lowtic)
				lowtic = nettics[i];

		if (lowtic < gametic)
			I_Error("TryRunTics: lowtic < gametic");

		// don't stay in here forever -- give the menu a chance to work
		if (I_GetTime () - entertic >= 20)
		{
			M_Ticker ();
			return;
		}

	} while (lowtic == gametic);

	if (netgame && lowtic == maketic && !drone)
	{
		int_632C8++;
		if (int_632C8 > 4)
		{
			int_632C8 = 0;
			gametime--;
		}
	}
	else
		int_632C8 = 0;

	do
	{
		if (advancedemo)
			D_DoAdvanceDemo ();
		M_Ticker ();
		G_Ticker ();
		gametic++;
		for (i = 0; i < numnetnodes; i++)
			if (nodeingame[i])
			{
				if (nettics[i] < gametic)
					I_Error("Run an improper tic");
				if (nettics[i] == gametic)
					break;
			}
	} while (i == numnetnodes);
}

/*
=============
=
= NetUpdate
=
= Builds ticcmds for console player
= sends out a packet
=============
*/

void NetUpdate (void)
{
	int             nowtime;
	int             newtics;

	if (singletics)
		return;         // singletic update is syncronous
	
//
// drone packets
//
	if (drone)
	{
		I_StartTic ();
		D_ProcessEvents( );

		netbuffer.player = (drone << 7) | (consoleplayer << 5) | netnode;
		netbuffer.tic = gametic + 8;
		SendPacket ();
		return;
	}

//
// check time
//
	nowtime = I_GetTime ();
	newtics = nowtime - gametime;
	if (newtics <= 0)                       // nothing new to update
		return;

	gametime = nowtime;

	while (newtics-- > 0)
	{
		I_StartTic ();
		D_ProcessEvents ();

		if (maketic - gametic >= 8)
			break;
		G_BuildTiccmd (&localcmds[maketic & (BACKUPTICS-1)]);
		maketic++;
	}

//
// send the packet to the other nodes
//
	netbuffer.player = (drone << 7) | (consoleplayer << 5) | netnode;
	netbuffer.tic = maketic;
	memcpy(netbuffer.cmds, localcmds, sizeof(localcmds));
	SendPacket ();
}


/*
===================
=
= GetPackets
=
===================
*/

char    exitmsg[80];

void GetPackets (void)
{
	int		netdrone;
	int		netconsole;
	int		netnode;

	while (GetPacket ())
	{
		netdrone = netbuffer.player & PL_DRONE;
		netconsole = (netbuffer.player >> 5) & 3;
		netnode = netbuffer.player & 31;
		
		//
		// check for exiting the game
		//
		if (netbuffer.tic == -1)
		{
			if (!nodeingame[netnode])
				continue;
			nodeingame[netnode] = 0;
			if (!netdrone)
			{
				playeringame[netconsole] = false;
				strcpy (exitmsg, "Player 1 left the game");
				exitmsg[7] += netconsole;
				players[consoleplayer].message = exitmsg;
			}
			continue;
		}

		if (nettics[netnode] > netbuffer.tic)
			continue;
		if (netbuffer.tic > gametic + BACKUPTICS)
			I_Error("GetPackets: netbuffer.tic > gametic + BACKUPTICS");
		nettics[netnode] = netbuffer.tic;
		if (!netdrone)
			memcpy(netcmds[netconsole], netbuffer.cmds, sizeof(netcmds[netconsole]));
	}
}

/*
===================
=
= D_CheckNetGame
=
= Works out player numbers among the net participants
===================
*/

extern	int			viewangleoffset;

void D_CheckNetGame (void)
{
	int netids[32];
	int netplayer[32];
	int i;
	int j;
	int console;
	int numplayers;
	int nodes;
	int dr;
	event_t *ev;

	i = M_CheckParm("-net");
	if (!i || i > myargc - 2)
	{
		playeringame[0] = true;
		nodeingame[0] = true;
		netgame = false;
		deathmatch = false;
		displayplayer = 0;
		consoleplayer = 0;
		numnetnodes = 1;
		return;
	}

	numnetnodes = myargv[i + 1][0] - '0';
	if (numnetnodes < 1 || numnetnodes > 32)
		I_Error("Invalid parameter: -net %s", myargv[i]);

	viewangleoffset = 0;
	consoleplayer = 0;
	drone = false;
	netgame = true;
	printf("I_InitNetwork: Initializing network for %i node game.\n", numnetnodes);

	i = M_CheckParm("-drone");
	if (i && i < myargc - 1)
	{
		drone = true;
		consoleplayer = displayplayer = myargv[i + 1][0] - '0';
		if (displayplayer < 0 || displayplayer >= numnetnodes)
			I_Error("Invalid parameter: -watch %s", myargv[i]);

		if (M_CheckParm("-right"))
			viewangleoffset = -ANG90;
		if (M_CheckParm("-left"))
			viewangleoffset = ANG90;
	}
	else if (M_CheckParm("-right"))
	{
		drone = true;
		displayplayer = 0;
		consoleplayer = 0;
		viewangleoffset = -ANG90;
	}
	else if (M_CheckParm("-left"))
	{
		drone = true;
		displayplayer = 0;
		consoleplayer = 0;
		viewangleoffset = ANG90;
	}

	if (M_CheckParm("-deathmatch"))
	{
		printf("DEATHMATCH network mode enabled.\n");
		deathmatch = true;
	}
	else
		deathmatch = false;

	memset(playeringame, 0, sizeof(playeringame));

	InitNetwork();

	nodes = 0;
	numplayers = 0;

	printf("Attempting to find all players for net play. Press ESC to exit.\n");
	printf("looking for player...");

	do
	{
		I_StartTic();
		for ( ; eventtail != eventhead ; eventtail = (++eventtail)&(MAXEVENTS-1) )
		{
			ev = &events[eventtail];
			if (ev->type == ev_keydown && ev->data1 == KEY_ESCAPE)
				I_Error ("Network game synchronization aborted.");
		}

		while (GetPacket())
		{
			if (netbuffer.tic > 16)
			{
				I_Error ("\n===========================================================================\n"
				"Can't start a network game on this port, one is in progress.\n"
				"You can specify an alternate port with the -port parameter\n"
				"===========================================================================\n");
			}

			for (i = 0; i < nodes; i++)
			{
				if (remotenetid == netids[i])
					break;
			}

			if (i != nodes)
				continue;

			if (netbuffer.player & PL_DRONE)
			{
				printf("found a drone for player %i\n", (netbuffer.player >> 5) & 3);
			}
			else
			{
				printf("found a player!\n");
				playeringame[numplayers++] = true;
			}

			for (i = 0; i < nodes; i++)
			{
				if (netids[i] > remotenetid)
					break;
			}
			for (j = nodes; j > i; j--)
			{
				netids[j] = netids[j - 1];
				netplayer[j] = netplayer[j - 1];
			}
			netids[j] = remotenetid;
			netplayer[j] = netbuffer.player;
			nodeingame[nodes++] = true;

			if (i == 0 && netbuffer.tic == 0)
			{
				startepisode = netbuffer.cmds[0].forwardmove;
				startmap = netbuffer.cmds[0].sidemove;
				startskill = netbuffer.cmds[0].angleturn;
				deathmatch = netbuffer.cmds[0].buttons;
				if (netbuffer.cmds[0].f_18 != VERSION)
				{
					I_Error("===========================================================================\n"
						"    All of the network players are not running the same VERSION of DOOM\n"
						"===========================================================================\n");
				}
			}

			if (nodes < numnetnodes)
				printf("looking for player...");
		}

		I_WaitVBL(1);

		netbuffer.tic = 0;
		netbuffer.player = (drone << 7) + (consoleplayer << 5);
		netbuffer.cmds[0].forwardmove = startepisode;
		netbuffer.cmds[0].sidemove = startmap;
		netbuffer.cmds[0].angleturn = startskill;
		netbuffer.cmds[0].buttons = deathmatch;
		netbuffer.cmds[0].f_18 = VERSION;

		SendPacket();
	} while (nodes < numnetnodes);

	console = 0;

	for (i = 0; i < numnetnodes; i++)
	{
		if (netplayer[i] & PL_DRONE)
		{
			dr = (netplayer[i] >> 5) & 3;
			if (dr >= numplayers)
				I_Error("A drone asked for player %i in a %i player game", dr, numplayers);

			if (netids[i] == localnetid)
			{
				netnode = i;
				displayplayer = dr;
				consoleplayer = dr;
			}
		}
		else
		{
			if (netids[i] == localnetid)
			{
				netnode = i;
				displayplayer = console;
				consoleplayer = console;
			}

			console++;
		}
	}

	if (console != numplayers)
		I_Error("Counted players != numplayers");

	if (!drone)
	{
		printf("Console is player %i.\n", consoleplayer);
	}
	else if (viewangleoffset == ANG90)
	{
		printf("Left side drone for player %i.\n", displayplayer);
	}
	else if (viewangleoffset == ANG270)
	{
		printf("Right side drone for player %i.\n", displayplayer);
	}
	else
	{
		printf("Forward drone for player %i.\n", displayplayer);
	}
}

void D_QuitNetGame(void)
{
	int i;

	if (!netgame || !usergame || consoleplayer == -1)
		return;

	netbuffer.player = (drone << 7) | (consoleplayer << 5) | netnode;
	netbuffer.tic = -1;

	for (i = 0; i < 10; i++)
	{
		SendPacket();
		I_WaitVBL(1);
	}
}

char unkbuffer[256];


#endif

/*
================
=
= FixedDiv
=
================
*/

fixed_t FixedDiv (fixed_t a, fixed_t b)
{
	if ( (abs(a)>>14) >= abs(b))
		return (a^b)<0 ? MININT : MAXINT;
	return FixedDiv2 (a,b);
}

/*
================
=
= D_Display
=
= draw current display, possibly wiping it from the previous
=
================
*/

// wipegamestate can be set to -1 to force a wipe on the next draw
int wipegamestate = GS_DEMOSCREEN;
extern boolean setsizeneeded;
extern int showMessages;
void R_ExecuteSetViewSize (void);

void D_Display (void)
{
	static boolean viewactivestate = false;
	static boolean menuactivestate = false;
	static boolean inhelpscreensstate = false;
	static boolean fullscreen = false;
	static int oldgamestate = -1;
	static int borderdrawcount;
	int nowtime;
	int tics;
	int wipestart;
	int y;
	boolean done;
	boolean wipe;
	boolean redrawsbar;

	if (nodrawers)
		return;                    // for comparative timing / profiling

	redrawsbar = false;

	// Change the view size if needed
	if (setsizeneeded)
	{
		R_ExecuteSetViewSize ();
		oldgamestate = -1;                      // force background redraw
		borderdrawcount = 3;
	}

	// save the current screen if about to wipe
	if (gamestate != wipegamestate)
	{
		wipe = true;
	}
	else
		wipe = false;

	if (wipe)
		wipe_StartScreen(0, 0, SCREENWIDTH, SCREENHEIGHT);

	if (gamestate == GS_LEVEL && gametic)
	{
		HU_Erase();
	}

//
// do buffered drawing
//
	switch (gamestate)
	{
	case GS_LEVEL:
		if (!gametic)
			break;
		if (automapactive)
		{
			AM_Drawer ();
		}
		if (wipe || (viewheight != 200 && fullscreen) )
			redrawsbar = true;
		if (inhelpscreensstate && !inhelpscreens)
			redrawsbar = true;              // just put away the help screen
		ST_Drawer (viewheight == 200, redrawsbar );
		fullscreen = viewheight == 200;
		break;
	case GS_INTERMISSION:
		WI_Drawer  ();
		break;
	case GS_FINALE:
		F_Drawer ();
		break;
	case GS_DEMOSCREEN:
		D_PageDrawer ();
		break;
	}
    
	// draw buffered stuff to screen
	I_UpdateNoBlit ();

#if (APPVER_DOOMREV < AV_DR_DM1666P)
	if (noblit)
		return;
#endif
	
	// draw the view directly
	if (gamestate == GS_LEVEL && !automapactive && gametic)
	{
		R_RenderPlayerView (&players[displayplayer]);
	}
	
	if (gamestate == GS_LEVEL && gametic)
	{
		HU_Drawer ();
	}
	
	// clean up border stuff
#if (APPVER_DOOMREV < AV_DR_DM1666P)
	if (gamestate != oldgamestate)
#else
	if (gamestate != oldgamestate && gamestate != GS_LEVEL)
#endif
	{
		I_SetPalette (W_CacheLumpName ("PLAYPAL",PU_CACHE));
	}
	
	// see if the border needs to be initially drawn
	if (gamestate == GS_LEVEL && oldgamestate != GS_LEVEL)
	{
		viewactivestate = false;        // view was not active
		R_FillBackScreen ();    // draw the pattern into the back screen
	}
	
	// see if the border needs to be updated to the screen
	if (gamestate == GS_LEVEL && !automapactive && scaledviewwidth != 320)
	{
		if (menuactive || menuactivestate || !viewactivestate)
			borderdrawcount = 3;
		if (borderdrawcount)
		{
			R_DrawViewBorder ();    // erase old menu stuff
			borderdrawcount--;
		}
	
	}
	
	menuactivestate = menuactive;
	viewactivestate = viewactive;
	inhelpscreensstate = inhelpscreens;
	oldgamestate = wipegamestate = gamestate;
	
	// draw pause pic
	if (paused)
	{
		if (automapactive)
			y = 4;
		else
			y = viewwindowy+4;
		V_DrawPatchDirect(viewwindowx+(scaledviewwidth-68)/2,
						  y,0,W_CacheLumpName ("M_PAUSE", PU_CACHE));
	}
	
	
	// menus go directly to the screen
	M_Drawer ();          // menu is drawn even on top of everything
	NetUpdate ();         // send out any new accumulation
	
	
	// normal update
	if (!wipe)
	{
		I_FinishUpdate ();              // page flip or blit buffer
		return;
	}
	
	// wipe update
	wipe_EndScreen(0, 0, SCREENWIDTH, SCREENHEIGHT);
	
	wipestart = I_GetTime () - 1;
	
	do
	{
		do
		{
			nowtime = I_GetTime ();
			tics = nowtime - wipestart;
		} while (!tics);
		wipestart = nowtime;
		done = wipe_ScreenWipe(wipe_Melt
							   , 0, 0, SCREENWIDTH, SCREENHEIGHT, tics);
		I_UpdateNoBlit ();
		M_Drawer ();                            // menu is drawn even on top of wipes
		I_FinishUpdate ();                      // page flip or blit buffer
	} while (!done);
}

/*
================
=
= D_DoomLoop
=
================
*/

void D_DoomLoop (void)
{
#if (APPVER_DOOMREV < AV_DR_DM12)
	I_InitGraphics();
#endif
#if (APPVER_DOOMREV >= AV_DR_DM1666P)
	if (demorecording)
		G_BeginRecording ();
#endif

	if (M_CheckParm ("-debugfile"))
	{
		char	filename[20];
		sprintf (filename, "debug%i.txt", consoleplayer);
#if (APPVER_DOOMREV >= AV_DR_DM1666P)
		printf ("debug output to: %s\n", filename);
#endif
		debugfile = fopen (filename,"w");
	}
#if (APPVER_DOOMREV >= AV_DR_DM12)
	I_InitGraphics ();
#endif
	while (1)
	{
		// frame syncronous IO operations
		I_StartFrame();

		// process one or more tics
		if (singletics)
		{
			I_StartTic ();
			D_ProcessEvents ();
#if (APPVER_DOOMREV < AV_DR_DM12)
			G_BuildTiccmd (&netcmds[consoleplayer][maketic&(BACKUPTICS-1)]);
#else
			G_BuildTiccmd (&netcmds[consoleplayer][maketic%BACKUPTICS]);
#endif
			if (advancedemo)
				D_DoAdvanceDemo ();
			M_Ticker ();
			G_Ticker ();
			gametic++;
			maketic++;
		}
		else
		{
			// will run at least one tic
			TryRunTics ();
		}

		// move positional sounds
		S_UpdateSounds(players[consoleplayer].mo);
		D_Display();
	}
}

/*
===============================================================================

						DEMO LOOP

===============================================================================
*/

int             demosequence;
int             pagetic;
char            *pagename;


/*
================
=
= D_PageTicker
=
= Handles timing for warped projection
=
================
*/

void D_PageTicker (void)
{
	if (--pagetic < 0)
		D_AdvanceDemo ();
}


/*
================
=
= D_PageDrawer
=
================
*/

void D_PageDrawer (void)
{
	V_DrawPatch (0,0, 0, W_CacheLumpName(pagename, PU_CACHE));
}

/*
=================
=
= D_AdvanceDemo
=
= Called after each demo or intro demosequence finishes
=================
*/

void D_AdvanceDemo (void)
{
	advancedemo = true;
}

void D_DoAdvanceDemo (void)
{
	players[consoleplayer].playerstate = PST_LIVE;  // don't reborn
	advancedemo = false;
	usergame = false;               // can't save / end game here
	paused = false;
	gameaction = ga_nothing;
#if (APPVER_DOOMREV >= AV_DR_DM19U) && (APPVER_DOOMREV < AV_DR_DM19F2)
	demosequence = (demosequence+1)%7;
#else
	demosequence = (demosequence+1)%6;
#endif
	switch (demosequence)
	{
		case 0:
#if (APPVER_DOOMREV >= AV_DR_DM1666P)
			if ( commercial )
				pagetic = 35 * 11;
			else
#endif
				pagetic = 170;
			gamestate = GS_DEMOSCREEN;
			pagename = "TITLEPIC";
#if (APPVER_DOOMREV >= AV_DR_DM1666P)
			if ( commercial )
				S_StartMusic(mus_dm2ttl);
			else
#endif
				S_StartMusic (mus_intro);
			break;
		case 1:
			G_DeferedPlayDemo ("demo1");
			break;
		case 2:
			pagetic = 200;
			gamestate = GS_DEMOSCREEN;
			pagename = "CREDIT";
			break;
		case 3:
			G_DeferedPlayDemo ("demo2");
			break;
		case 4:
#if (APPVER_DOOMREV < AV_DR_DM1666P)
			pagetic = 200;
			gamestate = GS_DEMOSCREEN;
			pagename = "HELP2";
#else
			gamestate = GS_DEMOSCREEN;
			if ( commercial )
			{
				pagetic = 35 * 11;
				pagename = "TITLEPIC";
				S_StartMusic(mus_dm2ttl);
			}
			else
			{
				pagetic = 200;
#if (APPVER_DOOMREV < AV_DR_DM19U)
				pagename = "HELP2";
#else
				pagename = "CREDIT";
#endif
			}
#endif
			break;
		case 5:
			G_DeferedPlayDemo ("demo3");
			break;
#if (APPVER_DOOMREV >= AV_DR_DM19U)
			// THE DEFINITIVE DOOM Special Edition demo
		case 6:
			G_DeferedPlayDemo ("demo4");
			break;
#endif
	}
}


/*
=================
=
= D_StartTitle
=
=================
*/

void D_StartTitle (void)
{
#if (APPVER_DOOMREV >= AV_DR_DM12)
	gameaction = ga_nothing;
#endif
	demosequence = -1;
	D_AdvanceDemo ();
}

#if (APPVER_DOOMREV < AV_DR_DM1666P)

void tprintf(char *msg, int fgcolor, int bgcolor)
{
	union REGS regs;
	int i;
	byte attr;
	int x;
	int y;

	attr = (bgcolor << 4) | fgcolor;
	regs.h.ah = 3;
	regs.h.bh = 0;
	int386(0x10, &regs, &regs);
	x = regs.h.dl;
	y = regs.h.dh;

	for (i = 0; i < strlen(msg); i++)
	{
		regs.h.ah = 9;
		regs.h.al = msg[i];
		regs.h.bl = attr;
		regs.h.bh = 0;
		regs.w.cx = 1;
		int386(0x10, &regs, &regs);
		if (++x > 79)
			x = 0;

		regs.h.ah = 2;
		regs.h.bh = 0;
		regs.h.dh = y;
		regs.h.dl = x;
		int386(0x10, &regs, &regs);
	}
}

#define mprintf printf

#else
char title[128]; //      print title for every printed line

int GetTextX(void)
{
	union REGS regs;
	regs.h.ah = 3;
	regs.h.bh = 0;
	int386(0x10, &regs, &regs);
	return regs.h.dl;
}

int GetTextY(void)
{
	union REGS regs;
	regs.h.ah = 3;
	regs.h.bh = 0;
	int386(0x10, &regs, &regs);
	return regs.h.dh;
}

void SetTextPos(int x, int y)
{
	union REGS regs;
	regs.h.ah = 2;
	regs.h.bh = 0;
	regs.h.dh = y;
	regs.h.dl = x;
	int386(0x10, &regs, &regs);
}

void tprintf(char *msg, int fgcolor, int bgcolor)
{
	union REGS regs;
	byte attr;
	int x;
	int y;
	int i;

	attr = (bgcolor << 4) | fgcolor;
	x = GetTextX();
	y = GetTextY();

	for (i = 0; i < strlen(msg); i++)
	{
		regs.h.ah = 9;
		regs.h.al = msg[i];
		regs.w.cx = 1;
		regs.h.bl = attr;
		regs.h.bh = 0;
		int386(0x10, &regs, &regs);
		if (++x > 79)
			x = 0;

		SetTextPos(x, y);
	}
}

void mprintf(char *msg)
{
	int x, y;
	printf(msg);

	x = GetTextX();
	y = GetTextY();

	SetTextPos(0, 0);

	tprintf(title, FGCOLOR, BGCOLOR);

	SetTextPos(x, y);
}
#endif

#if (APPVER_DOOMREV < AV_DR_DM1666P)
/*
==============
=
= D_CheckRecordFrom
=
= -recordfrom <savegame num> <demoname>
==============
*/

void D_CheckRecordFrom (void)
{
	int     p;
	char    file[256];

	p = M_CheckParm ("-recordfrom");
	if (!p || p > myargc-2)
		return;

	sprintf(file, "DOOMSAV%c.DSG",myargv[p+1][0]);
	G_LoadGame (file);
	G_DoLoadGame ();    // load the gameskill etc info from savegame

	G_RecordDemo (gameskill, 1, gameepisode, gamemap, myargv[p+2]);
	D_DoomLoop ();  // never returns
}
#endif

/*
===============
=
= D_AddFile
=
===============
*/
#if (APPVER_DOOMREV < AV_DR_DM1666P)
#if (APPVER_DOOMREV < AV_DR_DM12)
char *wadfiles[MAXWADFILES] = { "doom1.wad" };
char *basewart = "E1M1.wad";
#else
char *wadfiles[MAXWADFILES] = { "doom.wad" };
#endif
#if (APPVER_DOOMREV >= AV_DR_DM12)
char *basedefault = "default.cfg"; // default file
#endif
#endif

void D_AddFile(char *file)
{
	int numwadfiles;
	char *new;

	for(numwadfiles = 0; wadfiles[numwadfiles]; numwadfiles++);
	new = malloc(strlen(file)+1);
	strcpy(new, file);

#if (APPVER_DOOMREV < AV_DR_DM1666P)
	printf ("Adding external file %s.\n", new);
#endif

	wadfiles[numwadfiles] = new;
}

#if (APPVER_DOOMREV >= AV_DR_DM18FR) // Doom 95 debug info shows that it moved
void CheckBetaTest(void)
{
}
#endif


#if (APPVER_DOOMREV < AV_DR_DM19U)
#define DEVMAPS "e:/doom/"
#else
#define DEVMAPS "f:/doom/data_se/"
#endif
#define DEVDATA "c:/localid/"

#if (APPVER_DOOMREV >= AV_DR_DM1666P)
/*
=================
=
= IdentifyVersion
=
= Checks availability of IWAD files by name,
= to determine whether registered/commercial features
= should be executed (notably loading PWAD's).
=================
*/
void IdentifyVersion (void)
{

	char	*doom1wad, *doomwad, *doom2wad;
#if (APPVER_DOOMREV >= AV_DR_DM18FR)
#if (APPVER_DOOMREV < AV_DR_DM19F)
	char	*doom2fwad;
#else
	char	*doom2fwad, *plutoniawad, *tntwad;
#endif
#endif // AV_DR_DM18FR
	strcpy(basedefault,"default.cfg");
	doom1wad = "doom1.wad";
#if (APPVER_DOOMREV >= AV_DR_DM18FR)
	doom2fwad = "doom2f.wad";
#endif
	doom2wad = "doom2.wad";
#if (APPVER_DOOMREV >= AV_DR_DM19F)
	plutoniawad = "plutonia.wad";
	tntwad = "tnt.wad";
#endif
#if APPVER_CHEX
	doomwad = "chex.wad";
#else
	doomwad = "doom.wad";
#endif
	if (M_CheckParm ("-shdev"))
	{
		registered = false;
		shareware = true;
		devparm = true;
		D_AddFile (DEVDATA"doom1.wad");
#if (APPVER_DOOMREV < AV_DR_DM19U)
		D_AddFile (DEVMAPS"data/texture1.lmp");
		D_AddFile (DEVMAPS"data/pnames.lmp");
#else
		D_AddFile (DEVMAPS"data_se/texture1.lmp");
		D_AddFile (DEVMAPS"data_se/pnames.lmp");
#endif
		strcpy (basedefault,DEVDATA"default.cfg");
		return;
	}
	
	if (M_CheckParm ("-regdev"))
	{
		registered = true;
		devparm = true;
#if APPVER_CHEX
		D_AddFile (DEVDATA"chex.wad");
#else
		D_AddFile (DEVDATA"doom.wad");
#endif
#if (APPVER_DOOMREV < AV_DR_DM19U)
		D_AddFile (DEVMAPS"data/texture1.lmp");
		D_AddFile (DEVMAPS"data/texture2.lmp");
		D_AddFile (DEVMAPS"data/pnames.lmp");
#else
		D_AddFile (DEVMAPS"data_se/texture1.lmp");
		D_AddFile (DEVMAPS"data_se/texture2.lmp");
		D_AddFile (DEVMAPS"data_se/pnames.lmp");
#endif
		strcpy (basedefault,DEVDATA"default.cfg");
		return;
	}
	
	if (M_CheckParm ("-comdev"))
	{
		commercial = true;
		devparm = true;
#if (APPVER_DOOMREV >= AV_DR_DM19F)
		if(plutonia)
			D_AddFile (DEVDATA"plutonia.wad");
		else if(tnt)
			D_AddFile (DEVDATA"tnt.wad");
		else
#endif
			D_AddFile (DEVDATA"doom2.wad");
		    
		D_AddFile (DEVMAPS"cdata/texture1.lmp");
		D_AddFile (DEVMAPS"cdata/pnames.lmp");
		strcpy (basedefault,DEVDATA"default.cfg");
		return;
	}
	
#if (APPVER_DOOMREV >= AV_DR_DM18FR)
	if ( !access (doom2fwad,R_OK) )
	{
		commercial = true;
		// C'est ridicule!
		// Let's handle languages in config files, okay?
		french = true;
		printf("French version\n");
		D_AddFile (doom2fwad);
		return;
	}
#endif
	
	if ( !access (doom2wad,R_OK) )
	{
		commercial = true;
		D_AddFile (doom2wad);
		return;
	}
	
#if (APPVER_DOOMREV >= AV_DR_DM19F)
	if ( !access (plutoniawad, R_OK ) )
	{
		commercial = true;
		plutonia = true;
		D_AddFile (plutoniawad);
		return;
	}
	
	if ( !access (tntwad, R_OK ) )
	{
		commercial = true;
		tnt = true;
		D_AddFile (tntwad);
		return;
	}
#endif // APPVER_DOOMREV >= AV_DR_DM19F
	
	if ( !access (doomwad, R_OK ) )
	{
		registered = true;
		D_AddFile (doomwad);
		return;
	}
	
	if ( !access (doom1wad, R_OK ) )
	{
		shareware = true;
		D_AddFile (doom1wad);
		return;
	}
	
#if (APPVER_DOOMREV < AV_DR_DM18FR)
	I_Error("Game mode indeterminate\n");
#else
	printf("Game mode indeterminate.\n");
	exit(1);
#endif
}
#endif

#if (APPVER_DOOMREV >= AV_DR_DM1666P) && (APPVER_DOOMREV < AV_DR_DM18FR) // Doom 95 debug info shows that it moved
void CheckBetaTest(void)
{
}
#endif

#if (APPVER_DOOMREV >= AV_DR_DM1666P)
/*
=================
=
= Find a Response File
=
=================
*/
void FindResponseFile (void)
{
	int i;
#define MAXARGVS 100
	
	for (i = 1;i < myargc;i++)
		if (myargv[i][0] == '@')
		{
			FILE *handle;
			int size;
			int k;
			int index;
			int indexinfile;
			char *infile;
			char *file;
			char *moreargs[20];
			char *firstargv;
		
			// READ THE RESPONSE FILE INTO MEMORY
			handle = fopen (&myargv[i][1],"rb");
			if (!handle)
			{
#if (APPVER_DOOMREV < AV_DR_DM1666)
				I_Error ("No such response file!");
#else
				printf ("\nNo such response file!");
				exit(1);
#endif
			}
			printf("Found response file %s!\n",&myargv[i][1]);
			fseek (handle,0,SEEK_END);
			size = ftell(handle);
			fseek (handle,0,SEEK_SET);
			file = malloc (size);
			fread (file,size,1,handle);
			fclose (handle);
		
			// KEEP ALL CMDLINE ARGS FOLLOWING @RESPONSEFILE ARG
			for (index = 0,k = i+1; k < myargc; k++)
				moreargs[index++] = myargv[k];
		
			firstargv = myargv[0];
			myargv = malloc(sizeof(char *)*MAXARGVS);
			memset(myargv,0,sizeof(char *)*MAXARGVS);
			myargv[0] = firstargv;
		
			infile = file;
			indexinfile = k = 0;
			indexinfile++;  // SKIP PAST ARGV[0] (KEEP IT)
			do
			{
				myargv[indexinfile++] = infile+k;
				while(k < size &&
					((*(infile+k)>= ' '+1) && (*(infile+k)<='z')))
					k++;
				*(infile+k) = 0;
				while(k < size &&
					((*(infile+k)<= ' ') || (*(infile+k)>'z')))
					k++;
			} while(k < size);
		
			for (k = 0;k < index;k++)
				myargv[indexinfile++] = moreargs[k];
			myargc = indexinfile;
	
			// DISPLAY ARGS
			printf("%d command-line args:\n",myargc);
			for (k=1;k<myargc;k++)
				printf("%s\n",myargv[k]);
	
			break;
		}
}
#endif

/*
=================
=
= D_DoomMain
=
=================
*/

void D_DoomMain (void)
{
	union REGS regs;
	int p;
	char file[256];
#if (APPVER_DOOMREV < AV_DR_DM12)
	boolean autostart;
#endif

#if (APPVER_DOOMREV >= AV_DR_DM1666P)
	FindResponseFile ();

	IdentifyVersion ();
	
	setbuf (stdout, NULL);
	modifiedgame = false;
	
	nomonsters = M_CheckParm ("-nomonsters");
	respawnparm = M_CheckParm ("-respawn");
	fastparm = M_CheckParm ("-fast");
	devparm = M_CheckParm ("-devparm");
#if !APPVER_CHEX
	if (M_CheckParm ("-altdeath"))
		deathmatch = 2;
	else if (M_CheckParm ("-deathmatch"))
		deathmatch = 1;
#endif

	if (!commercial)
	{
		sprintf (title,
#if (APPVER_DOOMREV < AV_DR_DM17)
				 "                          "
				 "DOOM System Startup v%i.%i66"
				 "                          ",
#elif (APPVER_DOOMREV < AV_DR_DM19UP)
				 "                          "
				 "DOOM System Startup v%i.%i"
				 "                          ",
#elif (APPVER_DOOMREV < AV_DR_DM19U)
				 "                   "
				 "DOOM System Startup v%i.%i Special Edition"
				 "                          ",
#elif !APPVER_CHEX
				 "                         "
				 "The Ultimate DOOM Startup v%i.%i"
				 "                        ",
#else
				 "                         "
				 "Chex(R) Quest Startup"
				 "                        ",
#endif
				 VERSION/100,VERSION%100);
	}
#if (APPVER_DOOMREV >= AV_DR_DM19F)
	else if (plutonia)
	{
		sprintf (title,
				 "                   "
#if APPVER_CHEX
				 "Chex(R) Quest"
#else
				 "DOOM 2: Plutonia Experiment v%i.%i"
#endif
				 "                           ",
				 VERSION/100,VERSION%100);
	}
	else if (tnt)
	{
		sprintf (title,
				 "                     "
#if APPVER_CHEX
				 "Chex(R) Quest"
#else
				 "DOOM 2: TNT - Evilution v%i.%i"
#endif
				 "                           ",
				 VERSION/100,VERSION%100);
	}
#endif // APPVER_DOOMREV >= AV_DR_DM19F
	else
	{
		sprintf (title,
				 "                         "
#if (APPVER_DOOMREV < AV_DR_DM17)
				 "DOOM 2: Hell on Earth v%i.%i66"
				 "                          ",
#elif (APPVER_DOOMREV < AV_DR_DM17A)
				 "DOOM 2: Hell on Earth v%i.%i"
				 "                          ",
#elif (APPVER_DOOMREV < AV_DR_DM18FR)
				 "DOOM 2: Hell on Earth v%i.%ia"
				 "                          ",
#elif !APPVER_CHEX
				 "DOOM 2: Hell on Earth v%i.%i"
				 "                           ",
#else
				 "Chex(R) Quest"
				 "                           ",
#endif
				 VERSION/100,VERSION%100);
	}
#endif

	regs.w.ax = 3;
	int386 (0x10, &regs, &regs);

#if (APPVER_DOOMREV < AV_DR_DM1666P)
#define title file
#if (APPVER_DOOMREV < AV_DR_DM12)
	sprintf (title,
			 "                        "
			 "DOOM Operating System v%4.2f"
			 "                         ",
			 VERSION/100.0);
#else
	sprintf (title,
			 "                        "
			 "DOOM Operating System v%i.%i"
			 "                         ",
			 VERSION/100,VERSION%100);
#endif
#endif

	tprintf (title, FGCOLOR, BGCOLOR);

#if (APPVER_DOOMREV < AV_DR_DM19)
	printf ("\n");
#else
	printf ("\nP_Init: Checking cmd-line parameters...\n");
#endif

#if (APPVER_DOOMREV < AV_DR_DM1666P)
	setbuf(stdout, NULL);
	modifiedgame = false;

#if (APPVER_DOOMREV >= AV_DR_DM12)
	nomonsters = M_CheckParm("-nomonsters");
	respawnparm = M_CheckParm("-respawn");
#endif
	devparm = M_CheckParm("-devparm");
#endif
	
	if (devparm)
		mprintf(D_DEVSTR);

#if (APPVER_DOOMREV < AV_DR_DM1666P)
	if (devparm)
	{
#if (APPVER_DOOMREV < AV_DR_DM12)
		printf ("Relocated address of D_DoomMain: 0x%p.\n", (int)D_DoomMain);
#else
		extern char __begtext;
		printf ("program loaded at: 0x%p\n", &__begtext - 3);
#endif
	}
#endif

#if (APPVER_DOOMREV >= AV_DR_DM1666P)
	if (M_CheckParm("-cdrom"))
	{
		printf(D_CDROM);
#if (APPVER_DOOMREV < AV_DR_DM1666E)
		mkdir("c:doomdata");
#elif (APPVER_DOOMREV < AV_DR_DM17)
		mkdir("c:doomdata",0);
#else
		mkdir("c:\\doomdata",0);
#endif
		strcpy (basedefault,"c:/doomdata/default.cfg");
	}	
	
	// turbo option
	if ( (p=M_CheckParm ("-turbo")) )
	{
		int  scale = 200;
		extern int forwardmove[2];
		extern int sidemove[2];
	
		if (p<myargc-1)
			scale = atoi (myargv[p+1]);
		if (scale < 10)
			scale = 10;
		if (scale > 400)
			scale = 400;
		printf ("turbo scale: %i%%\n",scale);
		forwardmove[0] = forwardmove[0]*scale/100;
		forwardmove[1] = forwardmove[1]*scale/100;
		sidemove[0] = sidemove[0]*scale/100;
		sidemove[1] = sidemove[1]*scale/100;
	}
#endif
	
	// add any files specified on the command line with -file wadfile
	// to the wad list
	//
	// convenience hack to allow -wart e m to add a wad file
	// prepend a tilde to the filename so wadfile will be reloadable
	p = M_CheckParm ("-wart");
	if (p)
	{
		myargv[p][4] = 'p';     // big hack, change to -warp

		// Map name handling.
#if (APPVER_DOOMREV < AV_DR_DM1666P)
		sprintf (file,"E%cM%c.wad",
			myargv[p+1][0], myargv[p+2][0]);
		D_AddFile(file);
		printf("Warping to Episode %s, Map %s.\n",
			myargv[p+1],myargv[p+2]);
#else
		if (commercial)
		{
			p = atoi (myargv[p+1]);
			if (p<10)
				sprintf (file,"~"DEVMAPS"cdata/map0%i.wad", p);
			else
				sprintf (file,"~"DEVMAPS"cdata/map%i.wad", p);
		}
		else
		{
			sprintf (file,"~"DEVMAPS"E%cM%c.wad",
				myargv[p+1][0], myargv[p+2][0]);
			printf("Warping to Episode %s, Map %s.\n",
				myargv[p+1],myargv[p+2]);
		}
		D_AddFile (file);
#endif
	}
	
	p = M_CheckParm ("-file");
	if (p)
	{
		// the parms after p are wadfile/lump names,
		// until end of parms or another - preceded parm
		modifiedgame = true;            // homebrew levels
		while (++p != myargc && myargv[p][0] != '-')
			D_AddFile (myargv[p]);
	}
	
	p = M_CheckParm ("-playdemo");
	
	if (!p)
		p = M_CheckParm ("-timedemo");
	
	if (p && p < myargc-1)
	{
		sprintf (file,"%s.lmp", myargv[p+1]);
		D_AddFile (file);
		printf("Playing demo %s.lmp.\n",myargv[p+1]);
	}
	
	// get skill / episode / map from parms
	startskill = sk_medium;
	startepisode = 1;
	startmap = 1;
	autostart = false;

#if (APPVER_DOOMREV >= AV_DR_DM12 && APPVER_DOOMREV < AV_DR_DM1666P)
	if (M_CheckParm("-deathmatch"))
		deathmatch = true;
#endif
	
		
	p = M_CheckParm ("-skill");
	if (p && p < myargc-1)
	{
		startskill = myargv[p+1][0]-'1';
		autostart = true;
	}
	
	p = M_CheckParm ("-episode");
	if (p && p < myargc-1)
	{
		startepisode = myargv[p+1][0]-'0';
		startmap = 1;
		autostart = true;
	}

#if (APPVER_DOOMREV >= AV_DR_DM1666P)
	p = M_CheckParm ("-timer");
	if (p && p < myargc-1 && deathmatch)
	{
		int time;
		time = atoi(myargv[p+1]);
		printf("Levels will end after %d minute",time);
		if (time>1)
			printf("s");
		printf(".\n");
	}
	
	p = M_CheckParm ("-avg");
	if (p && p < myargc-1 && deathmatch)
		printf("Austin Virtual Gaming: Levels will end after 20 minutes\n");
#endif
	
	p = M_CheckParm ("-warp");
#if (APPVER_DOOMREV < AV_DR_DM1666P)
	if (devparm && p && p < myargc-2)
#else
	if (p && p < myargc-1)
#endif
	{
#if (APPVER_DOOMREV >= AV_DR_DM1666P)
		if (commercial)
			startmap = atoi (myargv[p+1]);
		else
#endif
		{
			startepisode = myargv[p+1][0]-'0';
			startmap = myargv[p+2][0]-'0';
		}
		autostart = true;
	}
	
	// init subsystems
	printf ("V_Init: allocate screens.\n");
	V_Init ();
	
	printf ("M_LoadDefaults: Load system defaults.\n");
	M_LoadDefaults ();              // load before initing other systems
	
	printf ("Z_Init: Init zone memory allocation daemon. \n");
#if (APPVER_DOOMREV < AV_DR_DM12)
	Z_Init (I_GetHeapSize());
#else
	Z_Init ();
#endif
	
	printf ("W_Init: Init WADfiles.\n");
	W_InitMultipleFiles (wadfiles);
	

#if (APPVER_DOOMREV >= AV_DR_DM1666P)
	// Check for -file in shareware
	if (modifiedgame)
	{
		// These are the lumps that will be checked in IWAD,
		// if any one is not present, execution will be aborted.
		char name[23][8]=
		{
			"e2m1","e2m2","e2m3","e2m4","e2m5","e2m6","e2m7","e2m8","e2m9",
			"e3m1","e3m3","e3m3","e3m4","e3m5","e3m6","e3m7","e3m8","e3m9",
			"dphoof","bfgga0","heada1","cybra1","spida1d1"
		};
		int i;
	
		if (shareware)
#if APPVER_CHEX
			I_Error("\nYou cannot -file with Chex(R) Quest "
				"version. Register!");
#else
			I_Error("\nYou cannot -file with the shareware "
				"version. Register!");
#endif
	
		// Check for fake IWAD with right name,
		// but w/o all the lumps of the registered version. 
		if (registered)
			for (i = 0;i < 23; i++)
				if (W_CheckNumForName(name[i])<0)
#if APPVER_CHEX
					I_Error("\nThis is Chex(R) Quest.");
#else
					I_Error("\nThis is not the registered version.");
#endif
	}
#if (APPVER_DOOMREV < AV_DR_DM1666E)
	if (commercial)
	{
		char name[5][8]=
		{
			"fatti5","map20","keena0","vileg1","skelg1"
		};
		int i;
		for (i = 0;i < 5; i++)
			if (W_CheckNumForName(name[i])<0)
				I_Error("\nThis is not the DOOM 2 wadfile.");
	}
#endif
#endif
	
#if !APPVER_CHEX
	// Iff additonal PWAD files are used, print modified banner
	if (modifiedgame)
	{
		/*m*/printf(
			"===========================================================================\n"
			"ATTENTION:  This version of DOOM has been modified.  If you would like to\n"
			"get a copy of the original game, call 1-800-IDGAMES or see the readme file.\n"
			"        You will not receive technical support for modified games.\n"
			"                      press enter to continue\n"
			"===========================================================================\n"
			);
		getchar ();
	}
#endif
	
	
	// Check and print which version is executed.
#if (APPVER_DOOMREV < AV_DR_DM1666P)
	if (W_CheckNumForName("E2M1") != -1)
	{
		printf("\tcommercial version.\n");
#if (APPVER_DOOMREV >= AV_DR_DM12)
		printf (
			"===========================================================================\n"
			"             This version is NOT SHAREWARE, do not distribute!\n"
			"         Please report software piracy to the SPA: 1-800-388-PIR8\n"
			"===========================================================================\n"
		);
#endif
		shareware = false;
	}
	else
	{
		printf("\tshareware version.\n");
		shareware = true;
	}
#else
	if (registered)
	{
		mprintf("\tregistered version.\n");
#if !APPVER_CHEX
		mprintf (
			"===========================================================================\n"
			"             This version is NOT SHAREWARE, do not distribute!\n"
			"         Please report software piracy to the SPA: 1-800-388-PIR8\n"
			"===========================================================================\n"
		);
#endif
	}
	if (shareware)
	{
		mprintf("\tshareware version.\n");
	}
	if (commercial)
	{
		mprintf("\tcommercial version.\n");
#if !APPVER_CHEX
		mprintf (
			"===========================================================================\n"
			"                            Do not distribute!\n"
			"         Please report software piracy to the SPA: 1-800-388-PIR8\n"
			"===========================================================================\n"
		);
#endif
	}
#endif
	
	mprintf ("M_Init: Init miscellaneous info.\n");
	M_Init ();
	
#if APPVER_CHEX
	mprintf ("R_Init: Init Chex(R) Quest refresh daemon - ");
#else
#if (APPVER_DOOMREV < AV_DR_DM1666P)
	mprintf ("R_Init: Init DOOM refresh daemon.");
#else
	mprintf ("R_Init: Init DOOM refresh daemon - ");
#endif
#endif
	R_Init ();
	
	mprintf ("\nP_Init: Init Playloop state.\n");
	P_Init ();
	
	mprintf ("I_Init: Setting up machine state.\n");
	I_Init ();
	
	mprintf ("D_CheckNetGame: Checking network game status.\n");
	D_CheckNetGame ();
	
	mprintf ("S_Init: Setting up sound.\n");
	S_Init (sfxVolume*8, musicVolume*8);
	
	mprintf ("HU_Init: Setting up heads up display.\n");
	HU_Init ();
	
	mprintf ("ST_Init: Init status bar.\n");
	ST_Init ();

#if (APPVER_DOOMREV < AV_DR_DM1666P)
	D_CheckRecordFrom ();
#endif

#if (APPVER_DOOMREV >= AV_DR_DM1666P)
	// check for a driver that wants intermission stats
	p = M_CheckParm ("-statcopy");
	if (p && p<myargc-1)
	{
		// for statistics driver
		extern void* statcopy;                            
	
		statcopy = (void*)atoi(myargv[p+1]);
		mprintf ("External statistics registered.\n");
	}
#endif
	
	// start the apropriate game based on parms
	p = M_CheckParm ("-record");

#if (APPVER_DOOMREV < AV_DR_DM1666P)
	if (devparm && p && p < myargc-1)
	{
		G_RecordDemo (startskill, 1, startepisode, startmap, myargv[p+1]);
		D_DoomLoop ();
	}
#else
	if (p && p < myargc-1)
	{
		G_RecordDemo (myargv[p+1]);
		autostart = true;
	}
#endif
	
	p = M_CheckParm ("-playdemo");
	if (p && p < myargc-1)
	{
		singledemo = true;              // quit after one demo
		G_DeferedPlayDemo (myargv[p+1]);
		D_DoomLoop ();  // never returns
	}
	
	p = M_CheckParm ("-timedemo");
	if (p && p < myargc-1)
	{
		G_TimeDemo (myargv[p+1]);
		D_DoomLoop ();  // never returns
	}
	
	p = M_CheckParm ("-loadgame");
	if (p && p < myargc-1)
	{
#if (APPVER_DOOMREV >= AV_DR_DM1666E)
		if (M_CheckParm("-cdrom"))
			sprintf(file, "c:\\doomdata\\"SAVEGAMENAME"%c.dsg",myargv[p+1][0]);
		else
#endif
			sprintf(file, SAVEGAMENAME"%c.dsg",myargv[p+1][0]);
		G_LoadGame (file);
	}
	
	
	if ( gameaction != ga_loadgame )
	{
		if (autostart || netgame)
			G_InitNew (startskill, startepisode, startmap);
		else
			D_StartTitle ();                // start up intro loop
	
	}
	
	D_DoomLoop ();  // never returns
}
